// PokeProf — Evolution Tree (branching evolutions)
// Auto-generated: 9/6/2026, 12:24:11 AM
// Entries: 109

const EVO_TREE = [
  {
    "fromDexId": 19,
    "fromFormName": "Alolan",
    "toDexId": 20,
    "evolveMethod": "level",
    "evolveLevel": 20,
    "evolveItem": null,
    "requiredGender": null,
    "toFormName": "Alolan",
    "evolveNickname": "Alolan"
  },
  {
    "fromDexId": 25,
    "fromFormName": null,
    "toDexId": 26,
    "evolveMethod": "use-item",
    "evolveLevel": null,
    "evolveItem": "thunder-stone",
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 25,
    "fromFormName": null,
    "toDexId": 26,
    "evolveMethod": "use-item",
    "evolveLevel": null,
    "evolveItem": "thunder-stone",
    "requiredGender": null,
    "toFormName": "Alolan",
    "evolveNickname": "Alolan"
  },
  {
    "fromDexId": 27,
    "fromFormName": "Alolan",
    "toDexId": 28,
    "evolveMethod": "use-item",
    "evolveLevel": null,
    "evolveItem": "ice-stone",
    "requiredGender": null,
    "toFormName": "Alolan",
    "evolveNickname": "Alolan"
  },
  {
    "fromDexId": 37,
    "fromFormName": "Alolan",
    "toDexId": 38,
    "evolveMethod": "use-item",
    "evolveLevel": null,
    "evolveItem": "ice-stone",
    "requiredGender": null,
    "toFormName": "Alolan",
    "evolveNickname": "Alolan"
  },
  {
    "fromDexId": 44,
    "fromFormName": null,
    "toDexId": 45,
    "evolveMethod": "use-item",
    "evolveLevel": null,
    "evolveItem": "leaf-stone",
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 44,
    "fromFormName": null,
    "toDexId": 182,
    "evolveMethod": "use-item",
    "evolveLevel": null,
    "evolveItem": "sun-stone",
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 50,
    "fromFormName": "Alolan",
    "toDexId": 51,
    "evolveMethod": "level",
    "evolveLevel": 26,
    "evolveItem": null,
    "requiredGender": null,
    "toFormName": "Alolan",
    "evolveNickname": "Alolan"
  },
  {
    "fromDexId": 52,
    "fromFormName": null,
    "toDexId": 53,
    "evolveMethod": "level",
    "evolveLevel": 28,
    "evolveItem": null,
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 52,
    "fromFormName": "Alolan",
    "toDexId": 53,
    "evolveMethod": "friendship",
    "evolveLevel": null,
    "evolveItem": null,
    "requiredGender": null,
    "toFormName": "Alolan",
    "evolveNickname": "Alolan"
  },
  {
    "fromDexId": 52,
    "fromFormName": "Galarian",
    "toDexId": 863,
    "evolveMethod": "level",
    "evolveLevel": 28,
    "evolveItem": null,
    "requiredGender": null,
    "toFormName": "Galarian",
    "evolveNickname": "Galarian"
  },
  {
    "fromDexId": 58,
    "fromFormName": "Hisuian",
    "toDexId": 59,
    "evolveMethod": "use-item",
    "evolveLevel": null,
    "evolveItem": "fire-stone",
    "requiredGender": null,
    "toFormName": "Hisuian",
    "evolveNickname": "Hisuian"
  },
  {
    "fromDexId": 61,
    "fromFormName": null,
    "toDexId": 62,
    "evolveMethod": "use-item",
    "evolveLevel": null,
    "evolveItem": "water-stone",
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 61,
    "fromFormName": null,
    "toDexId": 186,
    "evolveMethod": "use-item",
    "evolveLevel": null,
    "evolveItem": "kings-rock",
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 74,
    "fromFormName": "Alolan",
    "toDexId": 75,
    "evolveMethod": "level",
    "evolveLevel": 25,
    "evolveItem": null,
    "requiredGender": null,
    "toFormName": "Alolan",
    "evolveNickname": "Alolan"
  },
  {
    "fromDexId": 75,
    "fromFormName": "Alolan",
    "toDexId": 76,
    "evolveMethod": "use-item",
    "evolveLevel": null,
    "evolveItem": "link-cable",
    "requiredGender": null,
    "toFormName": "Alolan",
    "evolveNickname": "Alolan"
  },
  {
    "fromDexId": 77,
    "fromFormName": "Galarian",
    "toDexId": 78,
    "evolveMethod": "level",
    "evolveLevel": 40,
    "evolveItem": null,
    "requiredGender": null,
    "toFormName": "Galarian",
    "evolveNickname": "Galarian"
  },
  {
    "fromDexId": 79,
    "fromFormName": "Galarian",
    "toDexId": 80,
    "evolveMethod": "use-item",
    "evolveLevel": null,
    "evolveItem": "galarica-cuff",
    "requiredGender": null,
    "toFormName": "Galarian",
    "evolveNickname": "Galarian"
  },
  {
    "fromDexId": 79,
    "fromFormName": null,
    "toDexId": 80,
    "evolveMethod": "level",
    "evolveLevel": 37,
    "evolveItem": null,
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 79,
    "fromFormName": null,
    "toDexId": 199,
    "evolveMethod": "use-item",
    "evolveLevel": null,
    "evolveItem": "kings-rock",
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 79,
    "fromFormName": "Galarian",
    "toDexId": 199,
    "evolveMethod": "use-item",
    "evolveLevel": null,
    "evolveItem": "galarica-wreath",
    "requiredGender": null,
    "toFormName": "Galarian",
    "evolveNickname": "Galarian"
  },
  {
    "fromDexId": 83,
    "fromFormName": "Galarian",
    "toDexId": 865,
    "evolveMethod": "use-move",
    "evolveLevel": null,
    "evolveItem": "grass-physical",
    "requiredGender": null,
    "toFormName": "Galarian",
    "evolveNickname": "Galarian"
  },
  {
    "fromDexId": 88,
    "fromFormName": "Alolan",
    "toDexId": 89,
    "evolveMethod": "level",
    "evolveLevel": 38,
    "evolveItem": null,
    "requiredGender": null,
    "toFormName": "Alolan",
    "evolveNickname": "Alolan"
  },
  {
    "fromDexId": 100,
    "fromFormName": "Hisuian",
    "toDexId": 101,
    "evolveMethod": "use-item",
    "evolveLevel": null,
    "evolveItem": "leaf-stone",
    "requiredGender": null,
    "toFormName": "Hisuian",
    "evolveNickname": "Hisuian"
  },
  {
    "fromDexId": 102,
    "fromFormName": null,
    "toDexId": 103,
    "evolveMethod": "use-item",
    "evolveLevel": null,
    "evolveItem": "leaf-stone",
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 102,
    "fromFormName": null,
    "toDexId": 103,
    "evolveMethod": "use-item",
    "evolveLevel": null,
    "evolveItem": "leaf-stone",
    "requiredGender": null,
    "toFormName": "Alolan",
    "evolveNickname": "Alolan"
  },
  {
    "fromDexId": 104,
    "fromFormName": null,
    "toDexId": 105,
    "evolveMethod": "level",
    "evolveLevel": 28,
    "evolveItem": null,
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 104,
    "fromFormName": null,
    "toDexId": 105,
    "evolveMethod": "level",
    "evolveLevel": 28,
    "evolveItem": null,
    "requiredGender": null,
    "toFormName": "Alolan",
    "evolveNickname": "Alolan"
  },
  {
    "fromDexId": 109,
    "fromFormName": null,
    "toDexId": 110,
    "evolveMethod": "level",
    "evolveLevel": 35,
    "evolveItem": null,
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 109,
    "fromFormName": null,
    "toDexId": 110,
    "evolveMethod": "level",
    "evolveLevel": 35,
    "evolveItem": null,
    "requiredGender": null,
    "toFormName": "Galarian",
    "evolveNickname": "Galarian"
  },
  {
    "fromDexId": 439,
    "fromFormName": null,
    "toDexId": 122,
    "evolveMethod": "use-move",
    "evolveLevel": null,
    "evolveItem": "normal-physical",
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 439,
    "fromFormName": null,
    "toDexId": 122,
    "evolveMethod": "use-move",
    "evolveLevel": null,
    "evolveItem": "normal-physical",
    "requiredGender": null,
    "toFormName": "Galarian",
    "evolveNickname": "Galarian"
  },
  {
    "fromDexId": 122,
    "fromFormName": "Galarian",
    "toDexId": 866,
    "evolveMethod": "level",
    "evolveLevel": 42,
    "evolveItem": null,
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 123,
    "fromFormName": null,
    "toDexId": 212,
    "evolveMethod": "use-item",
    "evolveLevel": null,
    "evolveItem": "metal-coat",
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 123,
    "fromFormName": null,
    "toDexId": 900,
    "evolveMethod": "use-item",
    "evolveLevel": null,
    "evolveItem": "black-augurite",
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 133,
    "fromFormName": null,
    "toDexId": 134,
    "evolveMethod": "use-item",
    "evolveLevel": null,
    "evolveItem": "water-stone",
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 133,
    "fromFormName": null,
    "toDexId": 135,
    "evolveMethod": "use-item",
    "evolveLevel": null,
    "evolveItem": "thunder-stone",
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 133,
    "fromFormName": null,
    "toDexId": 136,
    "evolveMethod": "use-item",
    "evolveLevel": null,
    "evolveItem": "fire-stone",
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 133,
    "fromFormName": null,
    "toDexId": 196,
    "evolveMethod": "friendship-day",
    "evolveLevel": null,
    "evolveItem": null,
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 133,
    "fromFormName": null,
    "toDexId": 197,
    "evolveMethod": "friendship-night",
    "evolveLevel": null,
    "evolveItem": null,
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 133,
    "fromFormName": null,
    "toDexId": 470,
    "evolveMethod": "use-item",
    "evolveLevel": null,
    "evolveItem": "leaf-stone",
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 133,
    "fromFormName": null,
    "toDexId": 471,
    "evolveMethod": "use-item",
    "evolveLevel": null,
    "evolveItem": "ice-stone",
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 133,
    "fromFormName": null,
    "toDexId": 700,
    "evolveMethod": "use-move",
    "evolveLevel": null,
    "evolveItem": "fairy-special",
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 156,
    "fromFormName": null,
    "toDexId": 157,
    "evolveMethod": "level",
    "evolveLevel": 36,
    "evolveItem": null,
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 156,
    "fromFormName": null,
    "toDexId": 157,
    "evolveMethod": "level",
    "evolveLevel": 36,
    "evolveItem": null,
    "requiredGender": null,
    "toFormName": "Hisuian",
    "evolveNickname": "Hisuian"
  },
  {
    "fromDexId": 194,
    "fromFormName": null,
    "toDexId": 195,
    "evolveMethod": "level",
    "evolveLevel": 20,
    "evolveItem": null,
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 194,
    "fromFormName": "Paldean",
    "toDexId": 980,
    "evolveMethod": "level",
    "evolveLevel": 20,
    "evolveItem": null,
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 211,
    "fromFormName": "Hisuian",
    "toDexId": 904,
    "evolveMethod": "use-move",
    "evolveLevel": 60,
    "evolveItem": "poison-physical",
    "requiredGender": null,
    "toFormName": "Hisuian",
    "evolveNickname": "Hisuian"
  },
  {
    "fromDexId": 215,
    "fromFormName": "Hisuian",
    "toDexId": 903,
    "evolveMethod": "use-item",
    "evolveLevel": null,
    "evolveItem": "razor-claw",
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 215,
    "fromFormName": null,
    "toDexId": 461,
    "evolveMethod": "use-item",
    "evolveLevel": null,
    "evolveItem": "razor-claw",
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 222,
    "fromFormName": "Galarian",
    "toDexId": 864,
    "evolveMethod": "level",
    "evolveLevel": 38,
    "evolveItem": null,
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 236,
    "fromFormName": null,
    "toDexId": 106,
    "evolveMethod": "level",
    "evolveLevel": 20,
    "evolveItem": null,
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 236,
    "fromFormName": null,
    "toDexId": 107,
    "evolveMethod": "level",
    "evolveLevel": 20,
    "evolveItem": null,
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 236,
    "fromFormName": null,
    "toDexId": 237,
    "evolveMethod": "level",
    "evolveLevel": 20,
    "evolveItem": null,
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 263,
    "fromFormName": "Galarian",
    "toDexId": 264,
    "evolveMethod": "level",
    "evolveLevel": 20,
    "evolveItem": null,
    "requiredGender": null,
    "toFormName": "Galarian",
    "evolveNickname": "Galarian"
  },
  {
    "fromDexId": 264,
    "fromFormName": "Galarian",
    "toDexId": 862,
    "evolveMethod": "level",
    "evolveLevel": 35,
    "evolveItem": null,
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 263,
    "fromFormName": null,
    "toDexId": 264,
    "evolveMethod": "level",
    "evolveLevel": 20,
    "evolveItem": null,
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 265,
    "fromFormName": null,
    "toDexId": 266,
    "evolveMethod": "level",
    "evolveLevel": 7,
    "evolveItem": null,
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 265,
    "fromFormName": null,
    "toDexId": 268,
    "evolveMethod": "level",
    "evolveLevel": 7,
    "evolveItem": null,
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 281,
    "fromFormName": null,
    "toDexId": 282,
    "evolveMethod": "level",
    "evolveLevel": 30,
    "evolveItem": null,
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 281,
    "fromFormName": null,
    "toDexId": 475,
    "evolveMethod": "use-item",
    "evolveLevel": null,
    "evolveItem": "dawn-stone",
    "requiredGender": "M",
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 290,
    "fromFormName": null,
    "toDexId": 291,
    "evolveMethod": "level",
    "evolveLevel": 20,
    "evolveItem": null,
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 290,
    "fromFormName": null,
    "toDexId": 292,
    "evolveMethod": "shed",
    "evolveLevel": null,
    "evolveItem": null,
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 361,
    "fromFormName": null,
    "toDexId": 362,
    "evolveMethod": "level",
    "evolveLevel": 42,
    "evolveItem": null,
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 361,
    "fromFormName": null,
    "toDexId": 478,
    "evolveMethod": "use-item",
    "evolveLevel": null,
    "evolveItem": "dawn-stone",
    "requiredGender": "F",
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 366,
    "fromFormName": null,
    "toDexId": 367,
    "evolveMethod": "use-item",
    "evolveLevel": null,
    "evolveItem": "deep-sea-tooth",
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 366,
    "fromFormName": null,
    "toDexId": 368,
    "evolveMethod": "use-item",
    "evolveLevel": null,
    "evolveItem": "deep-sea-scale",
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 412,
    "fromFormName": null,
    "toDexId": 413,
    "evolveMethod": "level",
    "evolveLevel": 20,
    "evolveItem": null,
    "requiredGender": "F",
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 412,
    "fromFormName": null,
    "toDexId": 414,
    "evolveMethod": "level",
    "evolveLevel": 20,
    "evolveItem": null,
    "requiredGender": "M",
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 415,
    "fromFormName": null,
    "toDexId": 416,
    "evolveMethod": "level",
    "evolveLevel": 21,
    "evolveItem": null,
    "requiredGender": "F",
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 502,
    "fromFormName": null,
    "toDexId": 503,
    "evolveMethod": "level",
    "evolveLevel": 36,
    "evolveItem": null,
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 502,
    "fromFormName": null,
    "toDexId": 503,
    "evolveMethod": "level",
    "evolveLevel": 36,
    "evolveItem": null,
    "requiredGender": null,
    "toFormName": "Hisuian",
    "evolveNickname": "Hisuian"
  },
  {
    "fromDexId": 548,
    "fromFormName": null,
    "toDexId": 549,
    "evolveMethod": "use-item",
    "evolveLevel": null,
    "evolveItem": "sun-stone",
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 548,
    "fromFormName": null,
    "toDexId": 549,
    "evolveMethod": "use-item",
    "evolveLevel": null,
    "evolveItem": "sun-stone",
    "requiredGender": null,
    "toFormName": "Hisuian",
    "evolveNickname": "Hisuian"
  },
  {
    "fromDexId": 550,
    "fromFormName": "White Striped",
    "toDexId": 902,
    "evolveMethod": "use-move",
    "evolveLevel": 120,
    "evolveItem": "normal-physical",
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 554,
    "fromFormName": "Galarian",
    "toDexId": 555,
    "evolveMethod": "use-item",
    "evolveLevel": null,
    "evolveItem": "ice-stone",
    "requiredGender": null,
    "toFormName": "Galarian",
    "evolveNickname": "Galarian"
  },
  {
    "fromDexId": 554,
    "fromFormName": null,
    "toDexId": 555,
    "evolveMethod": "level",
    "evolveLevel": 35,
    "evolveItem": null,
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 562,
    "fromFormName": "Galarian",
    "toDexId": 867,
    "evolveMethod": "level",
    "evolveLevel": 34,
    "evolveItem": null,
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 562,
    "fromFormName": null,
    "toDexId": 563,
    "evolveMethod": "level",
    "evolveLevel": 34,
    "evolveItem": null,
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 570,
    "fromFormName": "Hisuian",
    "toDexId": 571,
    "evolveMethod": "level",
    "evolveLevel": 30,
    "evolveItem": null,
    "requiredGender": null,
    "toFormName": "Hisuian",
    "evolveNickname": "Hisuian"
  },
  {
    "fromDexId": 570,
    "fromFormName": null,
    "toDexId": 571,
    "evolveMethod": "level",
    "evolveLevel": 30,
    "evolveItem": null,
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 627,
    "fromFormName": null,
    "toDexId": 628,
    "evolveMethod": "level",
    "evolveLevel": 54,
    "evolveItem": null,
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 627,
    "fromFormName": null,
    "toDexId": 628,
    "evolveMethod": "level",
    "evolveLevel": 54,
    "evolveItem": null,
    "requiredGender": null,
    "toFormName": "Hisuian",
    "evolveNickname": "Hisuian"
  },
  {
    "fromDexId": 677,
    "fromFormName": null,
    "toDexId": 678,
    "evolveMethod": "level",
    "evolveLevel": 25,
    "evolveItem": null,
    "requiredGender": "M",
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 677,
    "fromFormName": null,
    "toDexId": 678,
    "evolveMethod": "level",
    "evolveLevel": 25,
    "evolveItem": null,
    "requiredGender": "F",
    "toFormName": "Female",
    "evolveNickname": "Female"
  },
  {
    "fromDexId": 704,
    "fromFormName": null,
    "toDexId": 705,
    "evolveMethod": "level",
    "evolveLevel": 40,
    "evolveItem": null,
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 704,
    "fromFormName": null,
    "toDexId": 705,
    "evolveMethod": "level",
    "evolveLevel": 40,
    "evolveItem": null,
    "requiredGender": null,
    "toFormName": "Hisuian",
    "evolveNickname": "Hisuian"
  },
  {
    "fromDexId": 705,
    "fromFormName": "Hisuian",
    "toDexId": 706,
    "evolveMethod": "level",
    "evolveLevel": 50,
    "evolveItem": null,
    "requiredGender": null,
    "toFormName": "Hisuian",
    "evolveNickname": "Hisuian"
  },
  {
    "fromDexId": 705,
    "fromFormName": null,
    "toDexId": 706,
    "evolveMethod": "level",
    "evolveLevel": 50,
    "evolveItem": null,
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 710,
    "fromFormName": "Small",
    "toDexId": 711,
    "evolveMethod": "use-item",
    "evolveLevel": null,
    "evolveItem": "link-cable",
    "requiredGender": null,
    "toFormName": "Small",
    "evolveNickname": "Small"
  },
  {
    "fromDexId": 710,
    "fromFormName": "Large",
    "toDexId": 711,
    "evolveMethod": "use-item",
    "evolveLevel": null,
    "evolveItem": "link-cable",
    "requiredGender": null,
    "toFormName": "Large",
    "evolveNickname": "Large"
  },
  {
    "fromDexId": 710,
    "fromFormName": "Super",
    "toDexId": 711,
    "evolveMethod": "use-item",
    "evolveLevel": null,
    "evolveItem": "link-cable",
    "requiredGender": null,
    "toFormName": "Super",
    "evolveNickname": "Super"
  },
  {
    "fromDexId": 712,
    "fromFormName": null,
    "toDexId": 713,
    "evolveMethod": "level",
    "evolveLevel": 37,
    "evolveItem": null,
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 712,
    "fromFormName": null,
    "toDexId": 713,
    "evolveMethod": "level",
    "evolveLevel": 37,
    "evolveItem": null,
    "requiredGender": null,
    "toFormName": "Hisuian",
    "evolveNickname": "Hisuian"
  },
  {
    "fromDexId": 723,
    "fromFormName": null,
    "toDexId": 724,
    "evolveMethod": "level",
    "evolveLevel": 34,
    "evolveItem": null,
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 723,
    "fromFormName": null,
    "toDexId": 724,
    "evolveMethod": "level",
    "evolveLevel": 34,
    "evolveItem": null,
    "requiredGender": null,
    "toFormName": "Hisuian",
    "evolveNickname": "Hisuian"
  },
  {
    "fromDexId": 744,
    "fromFormName": null,
    "toDexId": 745,
    "evolveMethod": "level",
    "evolveLevel": 25,
    "evolveItem": null,
    "requiredGender": null,
    "toFormName": "Midday",
    "evolveNickname": "Midday"
  },
  {
    "fromDexId": 744,
    "fromFormName": null,
    "toDexId": 745,
    "evolveMethod": "level",
    "evolveLevel": 25,
    "evolveItem": null,
    "requiredGender": null,
    "toFormName": "Midnight",
    "evolveNickname": "Midnight"
  },
  {
    "fromDexId": 744,
    "fromFormName": "Own Tempo",
    "toDexId": 745,
    "evolveMethod": "level",
    "evolveLevel": 25,
    "evolveItem": null,
    "requiredGender": null,
    "toFormName": "Dusk",
    "evolveNickname": "Dusk"
  },
  {
    "fromDexId": 757,
    "fromFormName": null,
    "toDexId": 758,
    "evolveMethod": "level",
    "evolveLevel": 33,
    "evolveItem": null,
    "requiredGender": "F",
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 790,
    "fromFormName": null,
    "toDexId": 791,
    "evolveMethod": "level",
    "evolveLevel": 53,
    "evolveItem": null,
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 790,
    "fromFormName": null,
    "toDexId": 792,
    "evolveMethod": "level",
    "evolveLevel": 53,
    "evolveItem": null,
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 840,
    "fromFormName": null,
    "toDexId": 841,
    "evolveMethod": "use-item",
    "evolveLevel": null,
    "evolveItem": "tart-apple",
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 840,
    "fromFormName": null,
    "toDexId": 842,
    "evolveMethod": "use-item",
    "evolveLevel": null,
    "evolveItem": "sweet-apple",
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 840,
    "fromFormName": null,
    "toDexId": 1011,
    "evolveMethod": "use-item",
    "evolveLevel": null,
    "evolveItem": "syrupy-apple",
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 891,
    "fromFormName": null,
    "toDexId": 892,
    "evolveMethod": "use-item",
    "evolveLevel": null,
    "evolveItem": "scroll-of-darkness",
    "requiredGender": null,
    "toFormName": "Single Strike",
    "evolveNickname": "Single Strike"
  },
  {
    "fromDexId": 891,
    "fromFormName": null,
    "toDexId": 892,
    "evolveMethod": "use-item",
    "evolveLevel": null,
    "evolveItem": "scroll-of-waters",
    "requiredGender": null,
    "toFormName": "Rapid Strike",
    "evolveNickname": "Rapid Strike"
  },
  {
    "fromDexId": 935,
    "fromFormName": null,
    "toDexId": 936,
    "evolveMethod": "use-item",
    "evolveLevel": null,
    "evolveItem": "auspicious-armor",
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  },
  {
    "fromDexId": 935,
    "fromFormName": null,
    "toDexId": 937,
    "evolveMethod": "use-item",
    "evolveLevel": null,
    "evolveItem": "malicious-armor",
    "requiredGender": null,
    "toFormName": null,
    "evolveNickname": null
  }
];

function getEvolutions(fromDexId) {
  return EVO_TREE.filter(e => e.fromDexId === fromDexId);
}
