// PokeProf — Items Database
// Auto-generated: 8/3/2026, 9:51:24 PM
// Entries: 73

const ITEMS_DATA = [
  {
    "itemId": "boulder-badge",
    "name": "Boulder Badge",
    "itemCategory": "badge",
    "description": "Proof of victory over a Gym Leader. Raises your aide's level cap by 10.",
    "effect": "raise-level-cap",
    "effectValue": null,
    "shopPrice": null,
    "sellPrice": null,
    "shopTier": null,
    "isConsumable": false,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": false,
    "usableInBattle": false,
    "sprite": null,
    "bagType": "Trainer"
  },
  {
    "itemId": "cascade-badge",
    "name": "Cascade Badge",
    "itemCategory": "badge",
    "description": "Proof of victory over a Gym Leader. Raises your aide's level cap by 10.",
    "effect": "raise-level-cap",
    "effectValue": null,
    "shopPrice": null,
    "sellPrice": null,
    "shopTier": null,
    "isConsumable": false,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": false,
    "usableInBattle": false,
    "sprite": null,
    "bagType": "Trainer"
  },
  {
    "itemId": "thunder-badge",
    "name": "Thunder Badge",
    "itemCategory": "badge",
    "description": "Proof of victory over a Gym Leader. Raises your aide's level cap by 10.",
    "effect": "raise-level-cap",
    "effectValue": null,
    "shopPrice": null,
    "sellPrice": null,
    "shopTier": null,
    "isConsumable": false,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": false,
    "usableInBattle": false,
    "sprite": null,
    "bagType": "Trainer"
  },
  {
    "itemId": "rainbow-badge",
    "name": "Rainbow Badge",
    "itemCategory": "badge",
    "description": "Proof of victory over a Gym Leader. Raises your aide's level cap by 10.",
    "effect": "raise-level-cap",
    "effectValue": null,
    "shopPrice": null,
    "sellPrice": null,
    "shopTier": null,
    "isConsumable": false,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": false,
    "usableInBattle": false,
    "sprite": null,
    "bagType": "Trainer"
  },
  {
    "itemId": "soul-badge",
    "name": "Soul Badge",
    "itemCategory": "badge",
    "description": "Proof of victory over a Gym Leader. Raises your aide's level cap by 10.",
    "effect": "raise-level-cap",
    "effectValue": null,
    "shopPrice": null,
    "sellPrice": null,
    "shopTier": null,
    "isConsumable": false,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": false,
    "usableInBattle": false,
    "sprite": null,
    "bagType": "Trainer"
  },
  {
    "itemId": "marsh-badge",
    "name": "Marsh Badge",
    "itemCategory": "badge",
    "description": "Proof of victory over a Gym Leader. Raises your aide's level cap by 10.",
    "effect": "raise-level-cap",
    "effectValue": null,
    "shopPrice": null,
    "sellPrice": null,
    "shopTier": null,
    "isConsumable": false,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": false,
    "usableInBattle": false,
    "sprite": null,
    "bagType": "Trainer"
  },
  {
    "itemId": "volcano-badge",
    "name": "Volcano Badge",
    "itemCategory": "badge",
    "description": "Proof of victory over a Gym Leader. Raises your aide's level cap by 10.",
    "effect": "raise-level-cap",
    "effectValue": null,
    "shopPrice": null,
    "sellPrice": null,
    "shopTier": null,
    "isConsumable": false,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": false,
    "usableInBattle": false,
    "sprite": null,
    "bagType": "Trainer"
  },
  {
    "itemId": "earth-badge",
    "name": "Earth Badge",
    "itemCategory": "badge",
    "description": "Proof of victory over a Gym Leader. Raises your aide's level cap by 10.",
    "effect": "raise-level-cap",
    "effectValue": null,
    "shopPrice": null,
    "sellPrice": null,
    "shopTier": null,
    "isConsumable": false,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": false,
    "usableInBattle": false,
    "sprite": null,
    "bagType": "Trainer"
  },
  {
    "itemId": "champion-badge",
    "name": "Champion Badge",
    "itemCategory": "badge",
    "description": "Proof of victory over a Gym Leader. Raises your aide's level cap by 10.",
    "effect": "raise-level-cap",
    "effectValue": null,
    "shopPrice": null,
    "sellPrice": null,
    "shopTier": null,
    "isConsumable": false,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": false,
    "usableInBattle": false,
    "sprite": null,
    "bagType": "Trainer"
  },
  {
    "itemId": "poke-ball",
    "name": "Poké Ball",
    "itemCategory": "ball",
    "description": "A basic ball for catching Pokémon",
    "effect": "catch",
    "effectValue": null,
    "shopPrice": 1,
    "sellPrice": null,
    "shopTier": "basic",
    "isConsumable": true,
    "catchRateModifier": 1,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "poke-ball",
    "bagType": "Professor"
  },
  {
    "itemId": "great-ball",
    "name": "Great Ball",
    "itemCategory": "ball",
    "description": "A better ball with a higher catch rate",
    "effect": "catch",
    "effectValue": null,
    "shopPrice": null,
    "sellPrice": null,
    "shopTier": null,
    "isConsumable": false,
    "catchRateModifier": 1.5,
    "requiresTarget": false,
    "usableInField": false,
    "usableInBattle": false,
    "sprite": "great-ball",
    "bagType": "Professor"
  },
  {
    "itemId": "master-ball",
    "name": "Master Ball",
    "itemCategory": "ball",
    "description": "Catches any Pokémon without fail",
    "effect": "catch-guaranteed",
    "effectValue": null,
    "shopPrice": null,
    "sellPrice": null,
    "shopTier": null,
    "isConsumable": false,
    "catchRateModifier": 255,
    "requiresTarget": false,
    "usableInField": false,
    "usableInBattle": false,
    "sprite": "master-ball",
    "bagType": "Professor"
  },
  {
    "itemId": "ultra-ball",
    "name": "Ultra Ball",
    "itemCategory": "ball",
    "description": "A high-performance ball with a great catch rate",
    "effect": "catch",
    "effectValue": null,
    "shopPrice": null,
    "sellPrice": null,
    "shopTier": null,
    "isConsumable": false,
    "catchRateModifier": 2,
    "requiresTarget": false,
    "usableInField": false,
    "usableInBattle": false,
    "sprite": "ultra-ball",
    "bagType": "Professor"
  },
  {
    "itemId": "poke-ball",
    "name": "Poké Ball",
    "itemCategory": "ball",
    "description": "A basic ball for catching Pokémon",
    "effect": "catch",
    "effectValue": null,
    "shopPrice": 1,
    "sellPrice": null,
    "shopTier": "lab",
    "isConsumable": true,
    "catchRateModifier": 1,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "poke-ball",
    "bagType": "Professor"
  },
  {
    "itemId": "potion",
    "name": "Potion",
    "itemCategory": "consumable",
    "description": "Restores 20 HP to one Pokémon",
    "effect": "heal-hp",
    "effectValue": 20,
    "shopPrice": 10,
    "sellPrice": null,
    "shopTier": "basic",
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": true,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "potion",
    "bagType": "Professor"
  },
  {
    "itemId": "revive",
    "name": "Revive",
    "itemCategory": "consumable",
    "description": "Revives a fainted Pokémon to half HP",
    "effect": "revive-half",
    "effectValue": null,
    "shopPrice": 50,
    "sellPrice": null,
    "shopTier": "basic",
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "revive",
    "bagType": "Professor"
  },
  {
    "itemId": "max-potion",
    "name": "Max Potion",
    "itemCategory": "consumable",
    "description": "Fully restores HP to one Pokémon",
    "effect": "heal-hp-full",
    "effectValue": null,
    "shopPrice": null,
    "sellPrice": null,
    "shopTier": null,
    "isConsumable": false,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": false,
    "usableInBattle": false,
    "sprite": "max-potion",
    "bagType": "Professor"
  },
  {
    "itemId": "max-revive",
    "name": "Max Revive",
    "itemCategory": "consumable",
    "description": "Revives a fainted Pokémon to full HP",
    "effect": "revive-full",
    "effectValue": null,
    "shopPrice": null,
    "sellPrice": null,
    "shopTier": null,
    "isConsumable": false,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": false,
    "usableInBattle": false,
    "sprite": "max-revive",
    "bagType": "Professor"
  },
  {
    "itemId": "super-potion",
    "name": "Super Potion",
    "itemCategory": "consumable",
    "description": "Restores 60 HP to one Pokémon",
    "effect": "heal-hp",
    "effectValue": 60,
    "shopPrice": null,
    "sellPrice": null,
    "shopTier": null,
    "isConsumable": false,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": false,
    "usableInBattle": false,
    "sprite": "super-potion",
    "bagType": "Professor"
  },
  {
    "itemId": "dawn-stone",
    "name": "Dawn Stone",
    "itemCategory": "evolutionItem",
    "description": "Causes certain Pokémon to evolve",
    "effect": "evolve-stone",
    "effectValue": null,
    "shopPrice": 100,
    "sellPrice": null,
    "shopTier": "full",
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "dawn-stone",
    "bagType": "Professor"
  },
  {
    "itemId": "dusk-stone",
    "name": "Dusk Stone",
    "itemCategory": "evolutionItem",
    "description": "Causes certain Pokémon to evolve",
    "effect": "evolve-stone",
    "effectValue": null,
    "shopPrice": 100,
    "sellPrice": null,
    "shopTier": "full",
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "dusk-stone",
    "bagType": "Professor"
  },
  {
    "itemId": "fire-stone",
    "name": "Fire Stone",
    "itemCategory": "evolutionItem",
    "description": "Causes certain Pokémon to evolve",
    "effect": "evolve-stone",
    "effectValue": null,
    "shopPrice": 100,
    "sellPrice": null,
    "shopTier": "full",
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "fire-stone",
    "bagType": "Professor"
  },
  {
    "itemId": "ice-stone",
    "name": "Ice Stone",
    "itemCategory": "evolutionItem",
    "description": "Causes certain Pokémon to evolve",
    "effect": "evolve-stone",
    "effectValue": null,
    "shopPrice": 100,
    "sellPrice": null,
    "shopTier": "full",
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "ice-stone",
    "bagType": "Professor"
  },
  {
    "itemId": "leaf-stone",
    "name": "Leaf Stone",
    "itemCategory": "evolutionItem",
    "description": "Causes certain Pokémon to evolve",
    "effect": "evolve-stone",
    "effectValue": null,
    "shopPrice": 100,
    "sellPrice": null,
    "shopTier": "full",
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "leaf-stone",
    "bagType": "Professor"
  },
  {
    "itemId": "link-cable",
    "name": "Link Cable",
    "itemCategory": "evolutionItem",
    "description": "Causes certain Pokémon to evolve",
    "effect": "evolve-trade",
    "effectValue": null,
    "shopPrice": 100,
    "sellPrice": null,
    "shopTier": "full",
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "link-cable",
    "bagType": "Professor"
  },
  {
    "itemId": "moon-stone",
    "name": "Moon Stone",
    "itemCategory": "evolutionItem",
    "description": "Causes certain Pokémon to evolve",
    "effect": "evolve-stone",
    "effectValue": null,
    "shopPrice": 100,
    "sellPrice": null,
    "shopTier": "full",
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "moon-stone",
    "bagType": "Professor"
  },
  {
    "itemId": "oval-stone",
    "name": "Oval Stone",
    "itemCategory": "evolutionItem",
    "description": "Causes certain Pokémon to evolve",
    "effect": "evolve-stone",
    "effectValue": null,
    "shopPrice": 100,
    "sellPrice": null,
    "shopTier": "full",
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "oval-stone",
    "bagType": "Professor"
  },
  {
    "itemId": "shiny-stone",
    "name": "Shiny Stone",
    "itemCategory": "evolutionItem",
    "description": "Causes certain Pokémon to evolve",
    "effect": "evolve-stone",
    "effectValue": null,
    "shopPrice": 100,
    "sellPrice": null,
    "shopTier": "full",
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "shiny-stone",
    "bagType": "Professor"
  },
  {
    "itemId": "sun-stone",
    "name": "Sun Stone",
    "itemCategory": "evolutionItem",
    "description": "Causes certain Pokémon to evolve",
    "effect": "evolve-stone",
    "effectValue": null,
    "shopPrice": 100,
    "sellPrice": null,
    "shopTier": "full",
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "sun-stone",
    "bagType": "Professor"
  },
  {
    "itemId": "thunder-stone",
    "name": "Thunder Stone",
    "itemCategory": "evolutionItem",
    "description": "Causes certain Pokémon to evolve",
    "effect": "evolve-stone",
    "effectValue": null,
    "shopPrice": 100,
    "sellPrice": null,
    "shopTier": "full",
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "thunder-stone",
    "bagType": "Professor"
  },
  {
    "itemId": "water-stone",
    "name": "Water Stone",
    "itemCategory": "evolutionItem",
    "description": "Causes certain Pokémon to evolve",
    "effect": "evolve-stone",
    "effectValue": null,
    "shopPrice": 100,
    "sellPrice": null,
    "shopTier": "full",
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "water-stone",
    "bagType": "Professor"
  },
  {
    "itemId": "kings-rock",
    "name": "King's Rock",
    "itemCategory": "evolutionItem",
    "description": "Causes certain Pokémon to evolve",
    "effect": "evolve-stone",
    "effectValue": null,
    "shopPrice": 100,
    "sellPrice": null,
    "shopTier": "full",
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "kings-rock",
    "bagType": "Professor"
  },
  {
    "itemId": "metal-coat",
    "name": "Metal Coat",
    "itemCategory": "evolutionItem",
    "description": "Causes certain Pokémon to evolve",
    "effect": "evolve-stone",
    "effectValue": null,
    "shopPrice": 100,
    "sellPrice": null,
    "shopTier": "full",
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "metal-coat",
    "bagType": "Professor"
  },
  {
    "itemId": "black-augurite",
    "name": "Black Augurite",
    "itemCategory": "evolutionItem",
    "description": "Causes certain Pokémon to evolve",
    "effect": "evolve-stone",
    "effectValue": null,
    "shopPrice": 100,
    "sellPrice": null,
    "shopTier": "full",
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "black-augurite",
    "bagType": "Professor"
  },
  {
    "itemId": "sweetTreat",
    "name": "Sweet Treat",
    "itemCategory": "evolutionItem",
    "description": "Causes certain Pokémon to evolve",
    "effect": "evolve-stone",
    "effectValue": null,
    "shopPrice": 100,
    "sellPrice": null,
    "shopTier": null,
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "sweetTreat",
    "bagType": "Professor"
  },
  {
    "itemId": "leadersCrest",
    "name": "Leader's Crest",
    "itemCategory": "evolutionItem",
    "description": "Causes certain Pokémon to evolve",
    "effect": "evolve-stone",
    "effectValue": null,
    "shopPrice": 100,
    "sellPrice": null,
    "shopTier": null,
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "leaders-crest",
    "bagType": "Professor"
  },
  {
    "itemId": "prismScale",
    "name": "Prism Scale",
    "itemCategory": "evolutionItem",
    "description": "Causes certain Pokémon to evolve",
    "effect": "evolve-stone",
    "effectValue": null,
    "shopPrice": 100,
    "sellPrice": null,
    "shopTier": null,
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "prism-scale",
    "bagType": "Professor"
  },
  {
    "itemId": "scrollOfDarkness",
    "name": "Scroll of Darkness",
    "itemCategory": "evolutionItem",
    "description": "Causes certain Pokémon to evolve",
    "effect": "evolve-stone",
    "effectValue": null,
    "shopPrice": 100,
    "sellPrice": null,
    "shopTier": null,
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "scroll-of-darkness",
    "bagType": "Professor"
  },
  {
    "itemId": "scrollOfWaters",
    "name": "Scroll of Waters",
    "itemCategory": "evolutionItem",
    "description": "Causes certain Pokémon to evolve",
    "effect": "evolve-stone",
    "effectValue": null,
    "shopPrice": 100,
    "sellPrice": null,
    "shopTier": null,
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "scroll-of-waters",
    "bagType": "Professor"
  },
  {
    "itemId": "protector",
    "name": "Protector",
    "itemCategory": "evolutionItem",
    "description": "Causes certain Pokémon to evolve",
    "effect": "evolve-stone",
    "effectValue": null,
    "shopPrice": 100,
    "sellPrice": null,
    "shopTier": "full",
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "protector",
    "bagType": "Professor"
  },
  {
    "itemId": "dragon-scale",
    "name": "Dragon Scale",
    "itemCategory": "evolutionItem",
    "description": "Causes certain Pokémon to evolve",
    "effect": "evolve-stone",
    "effectValue": null,
    "shopPrice": 100,
    "sellPrice": null,
    "shopTier": "full",
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "dragon-scale",
    "bagType": "Professor"
  },
  {
    "itemId": "electirizer",
    "name": "Electirizer",
    "itemCategory": "evolutionItem",
    "description": "Causes certain Pokémon to evolve",
    "effect": "evolve-stone",
    "effectValue": null,
    "shopPrice": 100,
    "sellPrice": null,
    "shopTier": "full",
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "electirizer",
    "bagType": "Professor"
  },
  {
    "itemId": "magmarizer",
    "name": "Magmarizer",
    "itemCategory": "evolutionItem",
    "description": "Causes certain Pokémon to evolve",
    "effect": "evolve-stone",
    "effectValue": null,
    "shopPrice": 100,
    "sellPrice": null,
    "shopTier": "full",
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "magmarizer",
    "bagType": "Professor"
  },
  {
    "itemId": "up-grade",
    "name": "Up Grade",
    "itemCategory": "evolutionItem",
    "description": "Causes certain Pokémon to evolve",
    "effect": "evolve-stone",
    "effectValue": null,
    "shopPrice": 100,
    "sellPrice": null,
    "shopTier": "full",
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "up-grade",
    "bagType": "Professor"
  },
  {
    "itemId": "razor-fang",
    "name": "Razor Fang",
    "itemCategory": "evolutionItem",
    "description": "Causes certain Pokémon to evolve",
    "effect": "evolve-stone",
    "effectValue": null,
    "shopPrice": 100,
    "sellPrice": null,
    "shopTier": "full",
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "razor-fang",
    "bagType": "Professor"
  },
  {
    "itemId": "razor-claw",
    "name": "Razor Claw",
    "itemCategory": "evolutionItem",
    "description": "Causes certain Pokémon to evolve",
    "effect": "evolve-stone",
    "effectValue": null,
    "shopPrice": 100,
    "sellPrice": null,
    "shopTier": "full",
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "razor-claw",
    "bagType": "Professor"
  },
  {
    "itemId": "peat-block",
    "name": "Peat Block",
    "itemCategory": "evolutionItem",
    "description": "Causes certain Pokémon to evolve",
    "effect": "evolve-stone",
    "effectValue": null,
    "shopPrice": 100,
    "sellPrice": null,
    "shopTier": "full",
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "peat-block",
    "bagType": "Professor"
  },
  {
    "itemId": "dubious-disc",
    "name": "Dubious Disc",
    "itemCategory": "evolutionItem",
    "description": "Causes certain Pokémon to evolve",
    "effect": "evolve-stone",
    "effectValue": null,
    "shopPrice": 100,
    "sellPrice": null,
    "shopTier": "full",
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "dubious-disc",
    "bagType": "Professor"
  },
  {
    "itemId": "reaper-cloth",
    "name": "Reaper Cloth",
    "itemCategory": "evolutionItem",
    "description": "Causes certain Pokémon to evolve",
    "effect": "evolve-stone",
    "effectValue": null,
    "shopPrice": 100,
    "sellPrice": null,
    "shopTier": "full",
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "reaper-cloth",
    "bagType": "Professor"
  },
  {
    "itemId": "deep-sea-tooth",
    "name": "Deep Sea Tooth",
    "itemCategory": "evolutionItem",
    "description": "Causes certain Pokémon to evolve",
    "effect": "evolve-stone",
    "effectValue": null,
    "shopPrice": 100,
    "sellPrice": null,
    "shopTier": "full",
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "deep-sea-tooth",
    "bagType": "Professor"
  },
  {
    "itemId": "sachet",
    "name": "Sachet",
    "itemCategory": "evolutionItem",
    "description": "Causes certain Pokémon to evolve",
    "effect": "evolve-stone",
    "effectValue": null,
    "shopPrice": 100,
    "sellPrice": null,
    "shopTier": "full",
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "sachet",
    "bagType": "Professor"
  },
  {
    "itemId": "whipped-dream",
    "name": "Whipped Dream",
    "itemCategory": "evolutionItem",
    "description": "Causes certain Pokémon to evolve",
    "effect": "evolve-stone",
    "effectValue": null,
    "shopPrice": 100,
    "sellPrice": null,
    "shopTier": "full",
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "whipped-dream",
    "bagType": "Professor"
  },
  {
    "itemId": "tart-apple",
    "name": "Tart Apple",
    "itemCategory": "evolutionItem",
    "description": "Causes certain Pokémon to evolve",
    "effect": "evolve-stone",
    "effectValue": null,
    "shopPrice": 100,
    "sellPrice": null,
    "shopTier": "full",
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "tart-apple",
    "bagType": "Professor"
  },
  {
    "itemId": "cracked-pot",
    "name": "Cracked Pot",
    "itemCategory": "evolutionItem",
    "description": "Causes certain Pokémon to evolve",
    "effect": "evolve-stone",
    "effectValue": null,
    "shopPrice": 100,
    "sellPrice": null,
    "shopTier": "full",
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "cracked-pot",
    "bagType": "Professor"
  },
  {
    "itemId": "metal-alloy",
    "name": "Metal Alloy",
    "itemCategory": "evolutionItem",
    "description": "Causes certain Pokémon to evolve",
    "effect": "evolve-stone",
    "effectValue": null,
    "shopPrice": 100,
    "sellPrice": null,
    "shopTier": "full",
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "metal-alloy",
    "bagType": "Professor"
  },
  {
    "itemId": "auspicious-armor",
    "name": "Auspicious Armor",
    "itemCategory": "evolutionItem",
    "description": "Causes certain Pokémon to evolve",
    "effect": "evolve-stone",
    "effectValue": null,
    "shopPrice": 100,
    "sellPrice": null,
    "shopTier": "full",
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "auspicious-armor",
    "bagType": "Professor"
  },
  {
    "itemId": "unremarkable-teacup",
    "name": "Unremarkable Teacup",
    "itemCategory": "evolutionItem",
    "description": "Causes certain Pokémon to evolve",
    "effect": "evolve-stone",
    "effectValue": null,
    "shopPrice": 100,
    "sellPrice": null,
    "shopTier": "full",
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "unremarkable-teacup",
    "bagType": "Professor"
  },
  {
    "itemId": "hm-cut",
    "name": "Cut",
    "itemCategory": "hm",
    "description": "Teaches a trainer's Pokémon to cut, enabling travel past bushes",
    "effect": "unlock-cut",
    "effectValue": null,
    "shopPrice": 100,
    "sellPrice": null,
    "shopTier": "full",
    "isConsumable": false,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "hm-cut",
    "bagType": "Trainer"
  },
  {
    "itemId": "hm-flash",
    "name": "Flash",
    "itemCategory": "hm",
    "description": "Teaches a trainer's Pokémon to light up dark caves",
    "effect": "unlock-flash",
    "effectValue": null,
    "shopPrice": 100,
    "sellPrice": null,
    "shopTier": "full",
    "isConsumable": false,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "hm-flash",
    "bagType": "Trainer"
  },
  {
    "itemId": "hm-fly",
    "name": "Fly",
    "itemCategory": "hm",
    "description": "Teaches a trainer's Pokémon to fly, enabling fast travel",
    "effect": "unlock-fly",
    "effectValue": null,
    "shopPrice": 100,
    "sellPrice": null,
    "shopTier": "full",
    "isConsumable": false,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "hm-fly",
    "bagType": "Trainer"
  },
  {
    "itemId": "hm-rockSmash",
    "name": "Rock Smash",
    "itemCategory": "hm",
    "description": "Teaches a trainer's Pokémon to smash rocks, clearing certain obstacles",
    "effect": "unlock-rockSmash",
    "effectValue": null,
    "shopPrice": 100,
    "sellPrice": null,
    "shopTier": "full",
    "isConsumable": false,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "hm-rockSmash",
    "bagType": "Trainer"
  },
  {
    "itemId": "hm-strength",
    "name": "Strength",
    "itemCategory": "hm",
    "description": "Teaches a trainer's Pokémon to push boulders, clearing certain obstacles",
    "effect": "unlock-strength",
    "effectValue": null,
    "shopPrice": 100,
    "sellPrice": null,
    "shopTier": "full",
    "isConsumable": false,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "hm-strength",
    "bagType": "Trainer"
  },
  {
    "itemId": "hm-surf",
    "name": "Surf",
    "itemCategory": "hm",
    "description": "Teaches a trainer's Pokémon to surf, enabling water travel",
    "effect": "unlock-surf",
    "effectValue": null,
    "shopPrice": 100,
    "sellPrice": null,
    "shopTier": "full",
    "isConsumable": false,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "hm-surf",
    "bagType": "Trainer"
  },
  {
    "itemId": "pokeFlute",
    "name": "Poké Flute",
    "itemCategory": "keyItem",
    "description": "Wakes a sleeping Pokémon blocking the path",
    "effect": "unlock-pokeFlute",
    "effectValue": null,
    "shopPrice": 100,
    "sellPrice": null,
    "shopTier": "full",
    "isConsumable": false,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "pokeFlute",
    "bagType": "Trainer"
  },
  {
    "itemId": "safariPass",
    "name": "Safari Pass",
    "itemCategory": "keyItem",
    "description": "Grants entry to the Safari Zone",
    "effect": "unlock-safariZone",
    "effectValue": null,
    "shopPrice": 100,
    "sellPrice": null,
    "shopTier": "full",
    "isConsumable": false,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "safariPass",
    "bagType": "Trainer"
  },
  {
    "itemId": "silphScope",
    "name": "Silph Scope",
    "itemCategory": "keyItem",
    "description": "Allows Professor to see through Ghost-type disguises",
    "effect": "unlock-silphScope",
    "effectValue": null,
    "shopPrice": 100,
    "sellPrice": null,
    "shopTier": "full",
    "isConsumable": false,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "silphScope",
    "bagType": "Trainer"
  },
  {
    "itemId": "sSTicket",
    "name": "S.S. Ticket",
    "itemCategory": "keyItem",
    "description": "Grants passage aboard the S.S. Anne",
    "effect": "unlock-ssTicket",
    "effectValue": null,
    "shopPrice": 100,
    "sellPrice": null,
    "shopTier": "full",
    "isConsumable": false,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "sSTicket",
    "bagType": "Trainer"
  },
  {
    "itemId": "goodRod",
    "name": "Good Rod",
    "itemCategory": "rod",
    "description": "Allows fishing for uncommon water Pokémon",
    "effect": "unlock-fish-good",
    "effectValue": null,
    "shopPrice": 100,
    "sellPrice": null,
    "shopTier": "full",
    "isConsumable": false,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "goodRod",
    "bagType": "Trainer"
  },
  {
    "itemId": "oldRod",
    "name": "Old Rod",
    "itemCategory": "rod",
    "description": "Allows fishing for common water Pokémon",
    "effect": "unlock-fish-old",
    "effectValue": null,
    "shopPrice": 100,
    "sellPrice": null,
    "shopTier": "full",
    "isConsumable": false,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "oldRod",
    "bagType": "Trainer"
  },
  {
    "itemId": "superRod",
    "name": "Super Rod",
    "itemCategory": "rod",
    "description": "Allows fishing for rare water Pokémon",
    "effect": "unlock-fish-super",
    "effectValue": null,
    "shopPrice": 100,
    "sellPrice": null,
    "shopTier": "full",
    "isConsumable": false,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "superRod",
    "bagType": "Trainer"
  },
  {
    "itemId": "tm",
    "name": "TM",
    "itemCategory": "tm",
    "description": "Upgrades, adds, or changes a Pokémon's equipped moves.",
    "effect": "modify-move",
    "effectValue": null,
    "shopPrice": 25,
    "sellPrice": null,
    "shopTier": "basic",
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": true,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "tm",
    "bagType": "Professor"
  },
  {
    "itemId": "bicycle",
    "name": "Bicycle",
    "itemCategory": "tool",
    "description": "Allows faster travel on roads",
    "effect": "unlock-bicycle",
    "effectValue": null,
    "shopPrice": 100,
    "sellPrice": null,
    "shopTier": "full",
    "isConsumable": false,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "bicycle",
    "bagType": "Trainer"
  },
  {
    "itemId": "coinCase",
    "name": "Coin Case",
    "itemCategory": "tool",
    "description": "Allows entry to the Game Corner",
    "effect": "unlock-coinCase",
    "effectValue": null,
    "shopPrice": 100,
    "sellPrice": null,
    "shopTier": "full",
    "isConsumable": false,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "coinCase",
    "bagType": "Trainer"
  }
];

function getItem(itemId) {
  return ITEMS_DATA.find(i => i.itemId === itemId) || null;
}

function getShopItems(locId) {
  if (typeof LOCATIONS === 'undefined') return [];
  const loc = getLocation(locId);
  if (!loc || !loc.shopTier) return [];
  const tierOrder = ['basic', 'full'];
  const tierIdx = tierOrder.indexOf(loc.shopTier);
  if (tierIdx < 0) return [];
  return ITEMS_DATA.filter(i => i.shopPrice && i.shopTier && tierOrder.indexOf(i.shopTier) <= tierIdx);
}
