// PokeProf — Items Database
// Auto-generated: 6/23/2026, 12:40:38 AM
// Entries: 24

const ITEMS_DATA = [
  {
    "itemId": "potion",
    "name": "Potion",
    "itemCategory": "consumable",
    "description": "Restores 20 HP to one Pokémon",
    "effect": "heal-hp",
    "effectValue": 20,
    "shopPrice": 10,
    "sellPrice": 5,
    "shopTier": "basic",
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": true,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "potion"
  },
  {
    "itemId": "super-potion",
    "name": "Super Potion",
    "itemCategory": "consumable",
    "description": "Restores 60 HP to one Pokémon",
    "effect": "heal-hp",
    "effectValue": 60,
    "shopPrice": 700,
    "sellPrice": 350,
    "shopTier": "basic",
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": true,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "super-potion"
  },
  {
    "itemId": "max-potion",
    "name": "Max Potion",
    "itemCategory": "consumable",
    "description": "Fully restores HP to one Pokémon",
    "effect": "heal-hp-full",
    "effectValue": null,
    "shopPrice": 1500,
    "sellPrice": 750,
    "shopTier": "full",
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": true,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "max-potion"
  },
  {
    "itemId": "revive",
    "name": "Revive",
    "itemCategory": "consumable",
    "description": "Revives a fainted Pokémon to half HP",
    "effect": "revive-half",
    "effectValue": null,
    "shopPrice": 50,
    "sellPrice": 25,
    "shopTier": "basic",
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": true,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "revive"
  },
  {
    "itemId": "max-revive",
    "name": "Max Revive",
    "itemCategory": "consumable",
    "description": "Revives a fainted Pokémon to full HP",
    "effect": "revive-full",
    "effectValue": null,
    "shopPrice": 3000,
    "sellPrice": 1500,
    "shopTier": "full",
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": true,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "max-revive"
  },
  {
    "itemId": "poke-ball",
    "name": "Poké Ball",
    "itemCategory": "ball",
    "description": "A basic ball for catching Pokémon",
    "effect": "catch",
    "effectValue": null,
    "shopPrice": 1,
    "sellPrice": 0,
    "shopTier": "basic",
    "isConsumable": true,
    "catchRateModifier": 1,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "poke-ball"
  },
  {
    "itemId": "great-ball",
    "name": "Great Ball",
    "itemCategory": "ball",
    "description": "A better ball with a higher catch rate",
    "effect": "catch",
    "effectValue": null,
    "shopPrice": 600,
    "sellPrice": 300,
    "shopTier": "basic",
    "isConsumable": true,
    "catchRateModifier": 1.5,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "great-ball"
  },
  {
    "itemId": "ultra-ball",
    "name": "Ultra Ball",
    "itemCategory": "ball",
    "description": "A high-performance ball with a great catch rate",
    "effect": "catch",
    "effectValue": null,
    "shopPrice": 1200,
    "sellPrice": 600,
    "shopTier": "full",
    "isConsumable": true,
    "catchRateModifier": 2,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "ultra-ball"
  },
  {
    "itemId": "master-ball",
    "name": "Master Ball",
    "itemCategory": "ball",
    "description": "Catches any Pokémon without fail",
    "effect": "catch-guaranteed",
    "effectValue": null,
    "shopPrice": 1000000,
    "sellPrice": 500000,
    "shopTier": "full",
    "isConsumable": true,
    "catchRateModifier": 255,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "master-ball"
  },
  {
    "itemId": "hm-surf",
    "name": "Surf",
    "itemCategory": "hm",
    "description": "Teaches a trainer's Pokémon to surf, enabling water travel",
    "effect": "unlock-surf",
    "effectValue": null,
    "shopPrice": 5000,
    "sellPrice": 0,
    "shopTier": "full",
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "hm-surf"
  },
  {
    "itemId": "hm-fly",
    "name": "Fly",
    "itemCategory": "hm",
    "description": "Teaches a trainer's Pokémon to fly, enabling fast travel",
    "effect": "unlock-fly",
    "effectValue": null,
    "shopPrice": 5000,
    "sellPrice": 0,
    "shopTier": "full",
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "hm-fly"
  },
  {
    "itemId": "fire-stone",
    "name": "Fire Stone",
    "itemCategory": "evolutionItem",
    "description": "Causes certain Pokémon to evolve",
    "effect": "evolve-stone",
    "effectValue": null,
    "shopPrice": 2100,
    "sellPrice": 1050,
    "shopTier": "full",
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": true,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "fire-stone"
  },
  {
    "itemId": "water-stone",
    "name": "Water Stone",
    "itemCategory": "evolutionItem",
    "description": "Causes certain Pokémon to evolve",
    "effect": "evolve-stone",
    "effectValue": null,
    "shopPrice": 2100,
    "sellPrice": 1050,
    "shopTier": "full",
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": true,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "water-stone"
  },
  {
    "itemId": "thunder-stone",
    "name": "Thunder Stone",
    "itemCategory": "evolutionItem",
    "description": "Causes certain Pokémon to evolve",
    "effect": "evolve-stone",
    "effectValue": null,
    "shopPrice": 2100,
    "sellPrice": 1050,
    "shopTier": "full",
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": true,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "thunder-stone"
  },
  {
    "itemId": "leaf-stone",
    "name": "Leaf Stone",
    "itemCategory": "evolutionItem",
    "description": "Causes certain Pokémon to evolve",
    "effect": "evolve-stone",
    "effectValue": null,
    "shopPrice": 2100,
    "sellPrice": 1050,
    "shopTier": "full",
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": true,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "leaf-stone"
  },
  {
    "itemId": "moon-stone",
    "name": "Moon Stone",
    "itemCategory": "evolutionItem",
    "description": "Causes certain Pokémon to evolve",
    "effect": "evolve-stone",
    "effectValue": null,
    "shopPrice": 2100,
    "sellPrice": 1050,
    "shopTier": "full",
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": true,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "moon-stone"
  },
  {
    "itemId": "sun-stone",
    "name": "Sun Stone",
    "itemCategory": "evolutionItem",
    "description": "Causes certain Pokémon to evolve",
    "effect": "evolve-stone",
    "effectValue": null,
    "shopPrice": 2100,
    "sellPrice": 1050,
    "shopTier": "full",
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": true,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "sun-stone"
  },
  {
    "itemId": "shiny-stone",
    "name": "Shiny Stone",
    "itemCategory": "evolutionItem",
    "description": "Causes certain Pokémon to evolve",
    "effect": "evolve-stone",
    "effectValue": null,
    "shopPrice": 2100,
    "sellPrice": 1050,
    "shopTier": "full",
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": true,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "shiny-stone"
  },
  {
    "itemId": "dusk-stone",
    "name": "Dusk Stone",
    "itemCategory": "evolutionItem",
    "description": "Causes certain Pokémon to evolve",
    "effect": "evolve-stone",
    "effectValue": null,
    "shopPrice": 2100,
    "sellPrice": 1050,
    "shopTier": "full",
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": true,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "dusk-stone"
  },
  {
    "itemId": "dawn-stone",
    "name": "Dawn Stone",
    "itemCategory": "evolutionItem",
    "description": "Causes certain Pokémon to evolve",
    "effect": "evolve-stone",
    "effectValue": null,
    "shopPrice": 2100,
    "sellPrice": 1050,
    "shopTier": "full",
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": true,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "dawn-stone"
  },
  {
    "itemId": "ice-stone",
    "name": "Ice Stone",
    "itemCategory": "evolutionItem",
    "description": "Causes certain Pokémon to evolve",
    "effect": "evolve-stone",
    "effectValue": null,
    "shopPrice": 2100,
    "sellPrice": 1050,
    "shopTier": "full",
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": true,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "ice-stone"
  },
  {
    "itemId": "oval-stone",
    "name": "Oval Stone",
    "itemCategory": "evolutionItem",
    "description": "Causes certain Pokémon to evolve",
    "effect": "evolve-stone",
    "effectValue": null,
    "shopPrice": 2100,
    "sellPrice": 1050,
    "shopTier": "full",
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": true,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "oval-stone"
  },
  {
    "itemId": "link-cable",
    "name": "Link Cable",
    "itemCategory": "evolutionItem",
    "description": "Causes certain Pokémon to evolve",
    "effect": "evolve-trade",
    "effectValue": null,
    "shopPrice": 2100,
    "sellPrice": 1050,
    "shopTier": "full",
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": true,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "link-cable"
  },
  {
    "itemId": "hm-cut",
    "name": "Cut",
    "itemCategory": "hm",
    "description": "Teaches a trainer's Pokémon to cut, enabling travel past bushes",
    "effect": "unlock-cut",
    "effectValue": null,
    "shopPrice": 5000,
    "sellPrice": 0,
    "shopTier": "full",
    "isConsumable": true,
    "catchRateModifier": null,
    "requiresTarget": false,
    "usableInField": true,
    "usableInBattle": false,
    "sprite": "hm-cut"
  }
];

function getItem(itemId) {
  return ITEMS_DATA.find(i => i.itemId === itemId) || null;
}

function getShopItems(locId) {
  if (typeof LOCATIONS === 'undefined') return [];
  const loc = getLocation(locId);
  if (!loc || !loc.shopTier) return [];
  const tierOrder = ['basic', 'full'];
  const tierIdx = tierOrder.indexOf(loc.shopTier);
  if (tierIdx < 0) return [];
  return ITEMS_DATA.filter(i => i.shopPrice && i.shopTier && tierOrder.indexOf(i.shopTier) <= tierIdx);
}
