// PokeProf — Locations Database
// Auto-generated: 7/31/2026, 10:48:28 PM
// Entries: 103

const LOCATIONS = [
  {
    "locationId": "palletTown",
    "name": "Pallet Town",
    "region": "Kanto",
    "heals": true,
    "shopTier": "lab",
    "travelTime": 1,
    "mapCol": 111,
    "mapRow": 97,
    "defaultEncounterMethod": "grass"
  },
  {
    "locationId": "route1",
    "name": "Route 1",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 6,
    "mapCol": 111,
    "mapRow": 96,
    "defaultEncounterMethod": "grass"
  },
  {
    "locationId": "route21",
    "name": "Route 21",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 15,
    "mapCol": 111,
    "mapRow": 98,
    "defaultEncounterMethod": "grass"
  },
  {
    "locationId": "viridianCity",
    "name": "Viridian City",
    "region": "Kanto",
    "heals": true,
    "shopTier": "basic",
    "travelTime": 1,
    "mapCol": 111,
    "mapRow": 95,
    "defaultEncounterMethod": "grass"
  },
  {
    "locationId": "celadonCity",
    "name": "Celadon City",
    "region": "Kanto",
    "heals": true,
    "shopTier": "full",
    "travelTime": 1,
    "mapCol": 117,
    "mapRow": 97,
    "defaultEncounterMethod": "grass"
  },
  {
    "locationId": "route2S",
    "name": "Route 2 - South",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 2,
    "mapCol": 111,
    "mapRow": 94,
    "defaultEncounterMethod": "grass"
  },
  {
    "locationId": "route2N",
    "name": "Route 2 - North",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 2,
    "mapCol": 111,
    "mapRow": 91,
    "defaultEncounterMethod": "grass"
  },
  {
    "locationId": "route22",
    "name": "Route 22",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 3,
    "mapCol": 110,
    "mapRow": 95,
    "defaultEncounterMethod": "grass"
  },
  {
    "locationId": "viridianForest",
    "name": "Viridian Forest",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 21,
    "mapCol": 111,
    "mapRow": 92,
    "defaultEncounterMethod": "grass"
  },
  {
    "locationId": "pewterCity",
    "name": "Pewter City",
    "region": "Kanto",
    "heals": true,
    "shopTier": "basic",
    "travelTime": 1,
    "mapCol": 111,
    "mapRow": 90,
    "defaultEncounterMethod": "grass"
  },
  {
    "locationId": "diglettsCaveN",
    "name": "Diglett's Cave  - North",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 1,
    "mapCol": 112,
    "mapRow": 91,
    "defaultEncounterMethod": "cave"
  },
  {
    "locationId": "diglettsCaveB1F",
    "name": "Diglett's Cave",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 15,
    "mapCol": 122,
    "mapRow": 91,
    "defaultEncounterMethod": "cave"
  },
  {
    "locationId": "route3",
    "name": "Route 3",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 4,
    "mapCol": 112,
    "mapRow": 90,
    "defaultEncounterMethod": "grass"
  },
  {
    "locationId": "route4W",
    "name": "Route 4 - West",
    "region": "Kanto",
    "heals": true,
    "shopTier": null,
    "travelTime": 1,
    "mapCol": 114,
    "mapRow": 90,
    "defaultEncounterMethod": "grass"
  },
  {
    "locationId": "route4",
    "name": "Route 4",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 3,
    "mapCol": 118,
    "mapRow": 90,
    "defaultEncounterMethod": "grass"
  },
  {
    "locationId": "diglettsCaveS",
    "name": "Diglett's Cave - South",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 1,
    "mapCol": 122,
    "mapRow": 99,
    "defaultEncounterMethod": "cave"
  },
  {
    "locationId": "mtMoon",
    "name": "Mt. Moon",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 14,
    "mapCol": 116,
    "mapRow": 90,
    "defaultEncounterMethod": "cave"
  },
  {
    "locationId": "mtMoonB1F",
    "name": "Mt. Moon - B1F",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 2,
    "mapCol": 117,
    "mapRow": 90,
    "defaultEncounterMethod": "cave"
  },
  {
    "locationId": "mtMoonB2F",
    "name": "Mt. Moon - B2F",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 10,
    "mapCol": 117,
    "mapRow": 89,
    "defaultEncounterMethod": "cave"
  },
  {
    "locationId": "ceruleanCity",
    "name": "Cerulean City",
    "region": "Kanto",
    "heals": true,
    "shopTier": "basic",
    "travelTime": 1,
    "mapCol": 120,
    "mapRow": 90,
    "defaultEncounterMethod": "grass"
  },
  {
    "locationId": "route24",
    "name": "Route 24",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 2,
    "mapCol": 120,
    "mapRow": 89,
    "defaultEncounterMethod": "grass"
  },
  {
    "locationId": "route25",
    "name": "Route 25",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 3,
    "mapCol": 121,
    "mapRow": 89,
    "defaultEncounterMethod": "grass"
  },
  {
    "locationId": "ceruleanCave",
    "name": "Cerulean Cave",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 11,
    "mapCol": 119,
    "mapRow": 89,
    "defaultEncounterMethod": "cave"
  },
  {
    "locationId": "ceruleanCave2F",
    "name": "Cerulean Cave - 2F",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 10,
    "mapCol": 119,
    "mapRow": 88,
    "defaultEncounterMethod": "cave"
  },
  {
    "locationId": "ceruleanCaveB1F",
    "name": "Cerulean Cave - B1F",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 10,
    "mapCol": 120,
    "mapRow": 88,
    "defaultEncounterMethod": "cave"
  },
  {
    "locationId": "route5",
    "name": "Route 5",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 3,
    "mapCol": 120,
    "mapRow": 95,
    "defaultEncounterMethod": "grass"
  },
  {
    "locationId": "undergroundPath5",
    "name": "Underground Path - 5",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 1,
    "mapCol": 121,
    "mapRow": 95,
    "defaultEncounterMethod": "grass"
  },
  {
    "locationId": "undergroundPath6",
    "name": "Underground Path - 6",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 1,
    "mapCol": 121,
    "mapRow": 99,
    "defaultEncounterMethod": "grass"
  },
  {
    "locationId": "route6",
    "name": "Route 6",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 5,
    "mapCol": 120,
    "mapRow": 99,
    "defaultEncounterMethod": "grass"
  },
  {
    "locationId": "vermillionCity",
    "name": "Vermillion City",
    "region": "Kanto",
    "heals": true,
    "shopTier": "basic",
    "travelTime": 1,
    "mapCol": 120,
    "mapRow": 100,
    "defaultEncounterMethod": "grass"
  },
  {
    "locationId": "sSAnne",
    "name": "S.S. Anne",
    "region": "Kanto",
    "heals": true,
    "shopTier": null,
    "travelTime": 4,
    "mapCol": 120,
    "mapRow": 101,
    "defaultEncounterMethod": "grass"
  },
  {
    "locationId": "route11",
    "name": "Route 11",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 9,
    "mapCol": 122,
    "mapRow": 100,
    "defaultEncounterMethod": "grass"
  },
  {
    "locationId": "route12",
    "name": "Route 12",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 17,
    "mapCol": 123,
    "mapRow": 100,
    "defaultEncounterMethod": "surf"
  },
  {
    "locationId": "route9",
    "name": "Route 9",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 5,
    "mapCol": 122,
    "mapRow": 90,
    "defaultEncounterMethod": "grass"
  },
  {
    "locationId": "route10N",
    "name": "Route 10 - North",
    "region": "Kanto",
    "heals": true,
    "shopTier": null,
    "travelTime": 2,
    "mapCol": 123,
    "mapRow": 90,
    "defaultEncounterMethod": "grass"
  },
  {
    "locationId": "powerPlant",
    "name": "Power Plant",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 15,
    "mapCol": 124,
    "mapRow": 90,
    "defaultEncounterMethod": "cave"
  },
  {
    "locationId": "rockTunnel",
    "name": "Rock Tunnel",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 6,
    "mapCol": 123,
    "mapRow": 91,
    "defaultEncounterMethod": "cave"
  },
  {
    "locationId": "rockTunnelB1FE",
    "name": "Rock Tunnel - B1FE",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 7,
    "mapCol": 123,
    "mapRow": 92,
    "defaultEncounterMethod": "cave"
  },
  {
    "locationId": "rockTunnel1FW",
    "name": "Rock Tunnel - 1FW",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 5,
    "mapCol": 123,
    "mapRow": 93,
    "defaultEncounterMethod": "cave"
  },
  {
    "locationId": "rockTunnelB1FW",
    "name": "Rock Tunnel - B1FW",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 6,
    "mapCol": 123,
    "mapRow": 94,
    "defaultEncounterMethod": "cave"
  },
  {
    "locationId": "rockTunnel1FS",
    "name": "Rock Tunnel - 1FS",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 4,
    "mapCol": 123,
    "mapRow": 95,
    "defaultEncounterMethod": "cave"
  },
  {
    "locationId": "route10S",
    "name": "Route 10 - South",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 1,
    "mapCol": 123,
    "mapRow": 96,
    "defaultEncounterMethod": "surf"
  },
  {
    "locationId": "lavenderTown",
    "name": "Lavender Town",
    "region": "Kanto",
    "heals": true,
    "shopTier": "basic",
    "travelTime": 1,
    "mapCol": 123,
    "mapRow": 97,
    "defaultEncounterMethod": "grass"
  },
  {
    "locationId": "pokemonTower",
    "name": "Pokemon Tower",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 1,
    "mapCol": 124,
    "mapRow": 97,
    "defaultEncounterMethod": "cave"
  },
  {
    "locationId": "pokemonTower2F",
    "name": "Pokemon Tower - 2F",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 1,
    "mapCol": 124,
    "mapRow": 98,
    "defaultEncounterMethod": "cave"
  },
  {
    "locationId": "pokemonTower3F",
    "name": "Pokemon Tower - 3F",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 1,
    "mapCol": 124,
    "mapRow": 99,
    "defaultEncounterMethod": "cave"
  },
  {
    "locationId": "pokemonTower4F",
    "name": "Pokemon Tower - 4F",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 1,
    "mapCol": 125,
    "mapRow": 99,
    "defaultEncounterMethod": "cave"
  },
  {
    "locationId": "pokemonTower5F",
    "name": "Pokemon Tower - 5F",
    "region": "Kanto",
    "heals": true,
    "shopTier": null,
    "travelTime": 1,
    "mapCol": 125,
    "mapRow": 98,
    "defaultEncounterMethod": "cave"
  },
  {
    "locationId": "pokemonTower6F",
    "name": "Pokemon Tower - 6F",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 1,
    "mapCol": 125,
    "mapRow": 97,
    "defaultEncounterMethod": "cave"
  },
  {
    "locationId": "pokemonTower7F",
    "name": "Pokemon Tower - 7F",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 1,
    "mapCol": 125,
    "mapRow": 96,
    "defaultEncounterMethod": "cave"
  },
  {
    "locationId": "route8",
    "name": "Route 8",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 4,
    "mapCol": 121,
    "mapRow": 97,
    "defaultEncounterMethod": "grass"
  },
  {
    "locationId": "undergroundPath8",
    "name": "Underground Path - 8",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 1,
    "mapCol": 121,
    "mapRow": 98,
    "defaultEncounterMethod": "grass"
  },
  {
    "locationId": "undergroundPath7",
    "name": "Underground Path - 7",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 1,
    "mapCol": 119,
    "mapRow": 98,
    "defaultEncounterMethod": "grass"
  },
  {
    "locationId": "route7",
    "name": "Route 7",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 2,
    "mapCol": 119,
    "mapRow": 97,
    "defaultEncounterMethod": "grass"
  },
  {
    "locationId": "saffronCity",
    "name": "Saffron City",
    "region": "Kanto",
    "heals": true,
    "shopTier": "basic",
    "travelTime": 1,
    "mapCol": 120,
    "mapRow": 97,
    "defaultEncounterMethod": "grass"
  },
  {
    "locationId": "silphCo",
    "name": "Silph Co",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 1,
    "mapCol": 119,
    "mapRow": 96,
    "defaultEncounterMethod": "grass"
  },
  {
    "locationId": "silphCo2F",
    "name": "Silph Co - 2F",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 1,
    "mapCol": 119,
    "mapRow": 95,
    "defaultEncounterMethod": "grass"
  },
  {
    "locationId": "silphCo3F",
    "name": "Silph Co - 3F",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 1,
    "mapCol": 118,
    "mapRow": 95,
    "defaultEncounterMethod": "grass"
  },
  {
    "locationId": "silphCo4F",
    "name": "Silph Co - 4F",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 1,
    "mapCol": 118,
    "mapRow": 96,
    "defaultEncounterMethod": "grass"
  },
  {
    "locationId": "silphCo5F",
    "name": "Silph Co - 5F",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 1,
    "mapCol": 117,
    "mapRow": 96,
    "defaultEncounterMethod": "grass"
  },
  {
    "locationId": "silphCo6F",
    "name": "Silph Co - 6F",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 1,
    "mapCol": 117,
    "mapRow": 95,
    "defaultEncounterMethod": "grass"
  },
  {
    "locationId": "silphCo7F",
    "name": "Silph Co - 7F",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 1,
    "mapCol": 117,
    "mapRow": 94,
    "defaultEncounterMethod": "grass"
  },
  {
    "locationId": "silphCo8F",
    "name": "Silph Co - 8F",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 1,
    "mapCol": 118,
    "mapRow": 94,
    "defaultEncounterMethod": "grass"
  },
  {
    "locationId": "silphCo9F",
    "name": "Silph Co - 9F",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 1,
    "mapCol": 119,
    "mapRow": 94,
    "defaultEncounterMethod": "grass"
  },
  {
    "locationId": "silphCo10F",
    "name": "Silph Co - 10F",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 1,
    "mapCol": 119,
    "mapRow": 93,
    "defaultEncounterMethod": "grass"
  },
  {
    "locationId": "silphCo11F",
    "name": "Silph Co - 11F",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 1,
    "mapCol": 118,
    "mapRow": 93,
    "defaultEncounterMethod": "grass"
  },
  {
    "locationId": "rocketHideout",
    "name": "Rocket Hideout",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 17,
    "mapCol": 117,
    "mapRow": 98,
    "defaultEncounterMethod": "grass"
  },
  {
    "locationId": "route13",
    "name": "Route 13",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 5,
    "mapCol": 123,
    "mapRow": 102,
    "defaultEncounterMethod": "grass"
  },
  {
    "locationId": "route14",
    "name": "Route 14",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 6,
    "mapCol": 122,
    "mapRow": 102,
    "defaultEncounterMethod": "grass"
  },
  {
    "locationId": "route15",
    "name": "Route 15",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 5,
    "mapCol": 118,
    "mapRow": 102,
    "defaultEncounterMethod": "grass"
  },
  {
    "locationId": "fuchsiaCity",
    "name": "Fuchsia City",
    "region": "Kanto",
    "heals": true,
    "shopTier": "basic",
    "travelTime": 1,
    "mapCol": 117,
    "mapRow": 102,
    "defaultEncounterMethod": "grass"
  },
  {
    "locationId": "safariZone1",
    "name": "Safari Zone - Area 1",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 9,
    "mapCol": 117,
    "mapRow": 101,
    "defaultEncounterMethod": "grass"
  },
  {
    "locationId": "safariZone2",
    "name": "Safari Zone - Area 2",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 9,
    "mapCol": 118,
    "mapRow": 101,
    "defaultEncounterMethod": "grass"
  },
  {
    "locationId": "safariZone3",
    "name": "Safari Zone - Area 3",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 9,
    "mapCol": 117,
    "mapRow": 100,
    "defaultEncounterMethod": "grass"
  },
  {
    "locationId": "safariZone4",
    "name": "Safari Zone - Area 4",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 9,
    "mapCol": 116,
    "mapRow": 101,
    "defaultEncounterMethod": "grass"
  },
  {
    "locationId": "route16",
    "name": "Route 16",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 2,
    "mapCol": 115,
    "mapRow": 97,
    "defaultEncounterMethod": "grass"
  },
  {
    "locationId": "route17",
    "name": "Route 17",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 8,
    "mapCol": 115,
    "mapRow": 99,
    "defaultEncounterMethod": "grass"
  },
  {
    "locationId": "route18",
    "name": "Route 18",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 4,
    "mapCol": 115,
    "mapRow": 102,
    "defaultEncounterMethod": "surf"
  },
  {
    "locationId": "route19",
    "name": "Route 19",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 8,
    "mapCol": 117,
    "mapRow": 103,
    "defaultEncounterMethod": "surf"
  },
  {
    "locationId": "route20E",
    "name": "Route 20 - East",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 5,
    "mapCol": 115,
    "mapRow": 103,
    "defaultEncounterMethod": "surf"
  },
  {
    "locationId": "route20W",
    "name": "Route 20 - West",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 7,
    "mapCol": 112,
    "mapRow": 103,
    "defaultEncounterMethod": "surf"
  },
  {
    "locationId": "seafoamIslandsW",
    "name": "Seafoam Islands - West",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 1,
    "mapCol": 114,
    "mapRow": 103,
    "defaultEncounterMethod": "cave"
  },
  {
    "locationId": "seafoamIslandsB1FW",
    "name": "Seafoam Islands - B1FW",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 5,
    "mapCol": 114,
    "mapRow": 104,
    "defaultEncounterMethod": "cave"
  },
  {
    "locationId": "seafoamIslandsB2FW",
    "name": "Seafoam Islands - B2FW",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 3,
    "mapCol": 115,
    "mapRow": 104,
    "defaultEncounterMethod": "cave"
  },
  {
    "locationId": "seafoamIslandsB3FW",
    "name": "Seafoam Islands - B3FW",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 3,
    "mapCol": 115,
    "mapRow": 105,
    "defaultEncounterMethod": "cave"
  },
  {
    "locationId": "seafoamIslandsB4F",
    "name": "Seafoam Islands - B4F",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 10,
    "mapCol": 114,
    "mapRow": 105,
    "defaultEncounterMethod": "cave"
  },
  {
    "locationId": "seafoamIslandsB3FE",
    "name": "Seafoam Islands - B3FE",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 7,
    "mapCol": 112,
    "mapRow": 105,
    "defaultEncounterMethod": "cave"
  },
  {
    "locationId": "seafoamIslandsB2FE",
    "name": "Seafoam Islands - B2FE",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 7,
    "mapCol": 112,
    "mapRow": 104,
    "defaultEncounterMethod": "cave"
  },
  {
    "locationId": "seafoamIslandsB1FE",
    "name": "Seafoam Islands - B1FE",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 5,
    "mapCol": 113,
    "mapRow": 104,
    "defaultEncounterMethod": "cave"
  },
  {
    "locationId": "seafoamIslandsE",
    "name": "Seafoam Islands - East",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 9,
    "mapCol": 113,
    "mapRow": 103,
    "defaultEncounterMethod": "cave"
  },
  {
    "locationId": "cinnabarIsland",
    "name": "Cinnabar Island",
    "region": "Kanto",
    "heals": true,
    "shopTier": "basic",
    "travelTime": 1,
    "mapCol": 111,
    "mapRow": 103,
    "defaultEncounterMethod": "grass"
  },
  {
    "locationId": "pokemonMansion",
    "name": "Pokemon Mansion",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 11,
    "mapCol": 110,
    "mapRow": 103,
    "defaultEncounterMethod": "cave"
  },
  {
    "locationId": "pokemonMansionB1F",
    "name": "Pokemon Mansion - B1F",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 11,
    "mapCol": 110,
    "mapRow": 104,
    "defaultEncounterMethod": "cave"
  },
  {
    "locationId": "pokemonMansion2F",
    "name": "Pokemon Mansion - 2F",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 11,
    "mapCol": 110,
    "mapRow": 102,
    "defaultEncounterMethod": "cave"
  },
  {
    "locationId": "pokemonMansion3F",
    "name": "Pokemon Mansion - 3F",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 7,
    "mapCol": 109,
    "mapRow": 102,
    "defaultEncounterMethod": "cave"
  },
  {
    "locationId": "route23",
    "name": "Route 23",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 19,
    "mapCol": 109,
    "mapRow": 95,
    "defaultEncounterMethod": "surf"
  },
  {
    "locationId": "victoryRoad",
    "name": "Victory Road - 1F",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 13,
    "mapCol": 109,
    "mapRow": 94,
    "defaultEncounterMethod": "cave"
  },
  {
    "locationId": "victoryRoad2F",
    "name": "Victory Road - 2F",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 18,
    "mapCol": 109,
    "mapRow": 93,
    "defaultEncounterMethod": "cave"
  },
  {
    "locationId": "victoryRoad3F",
    "name": "Victory Road - 3F",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 16,
    "mapCol": 109,
    "mapRow": 92,
    "defaultEncounterMethod": "cave"
  },
  {
    "locationId": "indigoPlateau",
    "name": "Indigo Plateau",
    "region": "Kanto",
    "heals": true,
    "shopTier": "basic",
    "travelTime": 1,
    "mapCol": 109,
    "mapRow": 91,
    "defaultEncounterMethod": "grass"
  },
  {
    "locationId": "gameCorner",
    "name": "Game Corner",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 1,
    "mapCol": 118,
    "mapRow": 98,
    "defaultEncounterMethod": "cave"
  },
  {
    "locationId": "fightingDojo",
    "name": "Fighting Dojo",
    "region": "Kanto",
    "heals": false,
    "shopTier": null,
    "travelTime": 1,
    "mapCol": 121,
    "mapRow": 96,
    "defaultEncounterMethod": "cave"
  },
  {
    "locationId": "pokemonDaycare",
    "name": "Pokemon Daycare",
    "region": "Kanto",
    "heals": true,
    "shopTier": null,
    "travelTime": 1,
    "mapCol": 121,
    "mapRow": 94,
    "defaultEncounterMethod": "cave"
  }
];

function getLocation(locationId) {
  return LOCATIONS.find(l => l.locationId === locationId) || null;
}
