// PokeProf — Trainers Database (Gym Battle System, v0.25)
// Auto-generated: 7/17/2026, 9:52:50 PM
// Entries: 27
// One row per team-slot: (trainerId, tier[, gauntletOrder]) groups into one battle roster.

const TRAINERS_DATA = [
  {
    "trainerId": "brock",
    "trainerName": "Brock",
    "locationId": "pewterCity",
    "tier": 1,
    "isGauntlet": false,
    "badgeItemId": "boulder-badge",
    "slotIndex": 1,
    "dexId": 74,
    "formName": null,
    "level": 12,
    "move1Power": 40,
    "move2Power": 40,
    "move3Power": null,
    "move4Power": null,
    "move1Type": "Normal",
    "move1Category": "Physical",
    "move2Type": "Normal",
    "move2Category": "Physical",
    "move3Type": null,
    "move3Category": null,
    "move4Type": null,
    "move4Category": null
  },
  {
    "trainerId": "brock",
    "trainerName": "Brock",
    "locationId": "pewterCity",
    "tier": 1,
    "isGauntlet": false,
    "badgeItemId": "boulder-badge",
    "slotIndex": 2,
    "dexId": 95,
    "formName": null,
    "level": 14,
    "move1Power": 40,
    "move2Power": 60,
    "move3Power": null,
    "move4Power": null,
    "move1Type": "Normal",
    "move1Category": "Physical",
    "move2Type": "Rock",
    "move2Category": "Physical",
    "move3Type": null,
    "move3Category": null,
    "move4Type": null,
    "move4Category": null
  },
  {
    "trainerId": "misty",
    "trainerName": "Misty",
    "locationId": "ceruleanCity",
    "tier": 2,
    "isGauntlet": false,
    "badgeItemId": "cascade-badge",
    "slotIndex": 1,
    "dexId": 120,
    "formName": null,
    "level": 18,
    "move1Power": 40,
    "move2Power": 60,
    "move3Power": null,
    "move4Power": null,
    "move1Type": "Normal",
    "move1Category": "Physical",
    "move2Type": "Water",
    "move2Category": "Special",
    "move3Type": null,
    "move3Category": null,
    "move4Type": null,
    "move4Category": null
  },
  {
    "trainerId": "misty",
    "trainerName": "Misty",
    "locationId": "ceruleanCity",
    "tier": 2,
    "isGauntlet": false,
    "badgeItemId": "cascade-badge",
    "slotIndex": 2,
    "dexId": 121,
    "formName": null,
    "level": 21,
    "move1Power": 50,
    "move2Power": 60,
    "move3Power": 60,
    "move4Power": null,
    "move1Type": "Normal",
    "move1Category": "Physical",
    "move2Type": "Water",
    "move2Category": "Special",
    "move3Type": "Normal",
    "move3Category": "Special",
    "move4Type": null,
    "move4Category": null
  },
  {
    "trainerId": "ltSurge",
    "trainerName": "Lt. Surge",
    "locationId": "vermillionCity",
    "tier": 3,
    "isGauntlet": false,
    "badgeItemId": "thunder-badge",
    "slotIndex": 1,
    "dexId": 100,
    "formName": null,
    "level": 21,
    "move1Power": 40,
    "move2Power": 40,
    "move3Power": 60,
    "move4Power": null,
    "move1Type": "Normal",
    "move1Category": "Special",
    "move2Type": "Normal",
    "move2Category": "Physical",
    "move3Type": "Electric",
    "move3Category": "Special",
    "move4Type": null,
    "move4Category": null
  },
  {
    "trainerId": "ltSurge",
    "trainerName": "Lt. Surge",
    "locationId": "vermillionCity",
    "tier": 3,
    "isGauntlet": false,
    "badgeItemId": "thunder-badge",
    "slotIndex": 2,
    "dexId": 25,
    "formName": null,
    "level": 18,
    "move1Power": 40,
    "move2Power": 60,
    "move3Power": null,
    "move4Power": null,
    "move1Type": "Normal",
    "move1Category": "Physical",
    "move2Type": "Electric",
    "move2Category": "Special",
    "move3Type": null,
    "move3Category": null,
    "move4Type": null,
    "move4Category": null
  },
  {
    "trainerId": "ltSurge",
    "trainerName": "Lt. Surge",
    "locationId": "vermillionCity",
    "tier": 3,
    "isGauntlet": false,
    "badgeItemId": "thunder-badge",
    "slotIndex": 3,
    "dexId": 26,
    "formName": null,
    "level": 24,
    "move1Power": 40,
    "move2Power": 60,
    "move3Power": null,
    "move4Power": null,
    "move1Type": "Normal",
    "move1Category": "Physical",
    "move2Type": "Electric",
    "move2Category": "Special",
    "move3Type": null,
    "move3Category": null,
    "move4Type": null,
    "move4Category": null
  },
  {
    "trainerId": "erika",
    "trainerName": "Erika",
    "locationId": "celadonCity",
    "tier": 4,
    "isGauntlet": false,
    "badgeItemId": "rainbow-badge",
    "slotIndex": 1,
    "dexId": 71,
    "formName": null,
    "level": 29,
    "move1Power": 75,
    "move2Power": 40,
    "move3Power": null,
    "move4Power": null,
    "move1Type": "Grass",
    "move1Category": "Special",
    "move2Type": "Poison",
    "move2Category": "Special",
    "move3Type": null,
    "move3Category": null,
    "move4Type": null,
    "move4Category": null
  },
  {
    "trainerId": "erika",
    "trainerName": "Erika",
    "locationId": "celadonCity",
    "tier": 4,
    "isGauntlet": false,
    "badgeItemId": "rainbow-badge",
    "slotIndex": 2,
    "dexId": 114,
    "formName": null,
    "level": 24,
    "move1Power": 75,
    "move2Power": 40,
    "move3Power": null,
    "move4Power": null,
    "move1Type": "Grass",
    "move1Category": "Special",
    "move2Type": "Normal",
    "move2Category": "Physical",
    "move3Type": null,
    "move3Category": null,
    "move4Type": null,
    "move4Category": null
  },
  {
    "trainerId": "erika",
    "trainerName": "Erika",
    "locationId": "celadonCity",
    "tier": 4,
    "isGauntlet": false,
    "badgeItemId": "rainbow-badge",
    "slotIndex": 3,
    "dexId": 45,
    "formName": null,
    "level": 29,
    "move1Power": 75,
    "move2Power": 40,
    "move3Power": null,
    "move4Power": null,
    "move1Type": "Grass",
    "move1Category": "Special",
    "move2Type": "Poison",
    "move2Category": "Special",
    "move3Type": null,
    "move3Category": null,
    "move4Type": null,
    "move4Category": null
  },
  {
    "trainerId": "koga",
    "trainerName": "Koga",
    "locationId": "fuchsiaCity",
    "tier": 5,
    "isGauntlet": false,
    "badgeItemId": "soul-badge",
    "slotIndex": 1,
    "dexId": 109,
    "formName": null,
    "level": 37,
    "move1Power": 65,
    "move2Power": 200,
    "move3Power": null,
    "move4Power": null,
    "move1Type": "Poison",
    "move1Category": "Special",
    "move2Type": "Normal",
    "move2Category": "Physical",
    "move3Type": null,
    "move3Category": null,
    "move4Type": null,
    "move4Category": null
  },
  {
    "trainerId": "koga",
    "trainerName": "Koga",
    "locationId": "fuchsiaCity",
    "tier": 5,
    "isGauntlet": false,
    "badgeItemId": "soul-badge",
    "slotIndex": 2,
    "dexId": 89,
    "formName": null,
    "level": 39,
    "move1Power": 65,
    "move2Power": null,
    "move3Power": null,
    "move4Power": null,
    "move1Type": "Poison",
    "move1Category": "Special",
    "move2Type": null,
    "move2Category": null,
    "move3Type": null,
    "move3Category": null,
    "move4Type": null,
    "move4Category": null
  },
  {
    "trainerId": "koga",
    "trainerName": "Koga",
    "locationId": "fuchsiaCity",
    "tier": 5,
    "isGauntlet": false,
    "badgeItemId": "soul-badge",
    "slotIndex": 3,
    "dexId": 109,
    "formName": null,
    "level": 37,
    "move1Power": 65,
    "move2Power": 200,
    "move3Power": null,
    "move4Power": null,
    "move1Type": "Poison",
    "move1Category": "Special",
    "move2Type": "Normal",
    "move2Category": "Physical",
    "move3Type": null,
    "move3Category": null,
    "move4Type": null,
    "move4Category": null
  },
  {
    "trainerId": "koga",
    "trainerName": "Koga",
    "locationId": "fuchsiaCity",
    "tier": 5,
    "isGauntlet": false,
    "badgeItemId": "soul-badge",
    "slotIndex": 4,
    "dexId": 110,
    "formName": null,
    "level": 43,
    "move1Power": 40,
    "move2Power": 65,
    "move3Power": null,
    "move4Power": null,
    "move1Type": "Normal",
    "move1Category": "Physical",
    "move2Type": "Poison",
    "move2Category": "Special",
    "move3Type": null,
    "move3Category": null,
    "move4Type": null,
    "move4Category": null
  },
  {
    "trainerId": "sabrina",
    "trainerName": "Sabrina",
    "locationId": "saffronCity",
    "tier": 6,
    "isGauntlet": false,
    "badgeItemId": "marsh-badge",
    "slotIndex": 1,
    "dexId": 64,
    "formName": null,
    "level": 38,
    "move1Power": 60,
    "move2Power": 65,
    "move3Power": null,
    "move4Power": null,
    "move1Type": "Psychic",
    "move1Category": "Special",
    "move2Type": "Psychic",
    "move2Category": "Special",
    "move3Type": null,
    "move3Category": null,
    "move4Type": null,
    "move4Category": null
  },
  {
    "trainerId": "sabrina",
    "trainerName": "Sabrina",
    "locationId": "saffronCity",
    "tier": 6,
    "isGauntlet": false,
    "badgeItemId": "marsh-badge",
    "slotIndex": 2,
    "dexId": 122,
    "formName": null,
    "level": 37,
    "move1Power": 65,
    "move2Power": null,
    "move3Power": null,
    "move4Power": null,
    "move1Type": "Psychic",
    "move1Category": "Special",
    "move2Type": null,
    "move2Category": null,
    "move3Type": null,
    "move3Category": null,
    "move4Type": null,
    "move4Category": null
  },
  {
    "trainerId": "sabrina",
    "trainerName": "Sabrina",
    "locationId": "saffronCity",
    "tier": 6,
    "isGauntlet": false,
    "badgeItemId": "marsh-badge",
    "slotIndex": 3,
    "dexId": 49,
    "formName": null,
    "level": 38,
    "move1Power": 65,
    "move2Power": 80,
    "move3Power": 40,
    "move4Power": null,
    "move1Type": "Psychic",
    "move1Category": "Special",
    "move2Type": "Bug",
    "move2Category": "Physical",
    "move3Type": "Flying",
    "move3Category": "Special",
    "move4Type": null,
    "move4Category": null
  },
  {
    "trainerId": "sabrina",
    "trainerName": "Sabrina",
    "locationId": "saffronCity",
    "tier": 6,
    "isGauntlet": false,
    "badgeItemId": "marsh-badge",
    "slotIndex": 4,
    "dexId": 65,
    "formName": null,
    "level": 43,
    "move1Power": 60,
    "move2Power": 90,
    "move3Power": null,
    "move4Power": null,
    "move1Type": "Psychic",
    "move1Category": "Special",
    "move2Type": "Psychic",
    "move2Category": "Special",
    "move3Type": null,
    "move3Category": null,
    "move4Type": null,
    "move4Category": null
  },
  {
    "trainerId": "blaine",
    "trainerName": "Blaine",
    "locationId": "cinnabarIsland",
    "tier": 7,
    "isGauntlet": false,
    "badgeItemId": "volcano-badge",
    "slotIndex": 1,
    "dexId": 58,
    "formName": null,
    "level": 42,
    "move1Power": 110,
    "move2Power": 90,
    "move3Power": 60,
    "move4Power": null,
    "move1Type": "Fire",
    "move1Category": "Special",
    "move2Type": "Normal",
    "move2Category": "Physical",
    "move3Type": "Dark",
    "move3Category": "Physical",
    "move4Type": null,
    "move4Category": null
  },
  {
    "trainerId": "blaine",
    "trainerName": "Blaine",
    "locationId": "cinnabarIsland",
    "tier": 7,
    "isGauntlet": false,
    "badgeItemId": "volcano-badge",
    "slotIndex": 2,
    "dexId": 77,
    "formName": null,
    "level": 40,
    "move1Power": 110,
    "move2Power": 85,
    "move3Power": 65,
    "move4Power": null,
    "move1Type": "Fire",
    "move1Category": "Special",
    "move2Type": "Flying",
    "move2Category": "Physical",
    "move3Type": "Normal",
    "move3Category": "Physical",
    "move4Type": null,
    "move4Category": null
  },
  {
    "trainerId": "blaine",
    "trainerName": "Blaine",
    "locationId": "cinnabarIsland",
    "tier": 7,
    "isGauntlet": false,
    "badgeItemId": "volcano-badge",
    "slotIndex": 3,
    "dexId": 78,
    "formName": null,
    "level": 42,
    "move1Power": 110,
    "move2Power": 85,
    "move3Power": 65,
    "move4Power": null,
    "move1Type": "Fire",
    "move1Category": "Special",
    "move2Type": "Flying",
    "move2Category": "Physical",
    "move3Type": "Normal",
    "move3Category": "Physical",
    "move4Type": null,
    "move4Category": null
  },
  {
    "trainerId": "blaine",
    "trainerName": "Blaine",
    "locationId": "cinnabarIsland",
    "tier": 7,
    "isGauntlet": false,
    "badgeItemId": "volcano-badge",
    "slotIndex": 4,
    "dexId": 59,
    "formName": null,
    "level": 47,
    "move1Power": 110,
    "move2Power": 90,
    "move3Power": 60,
    "move4Power": null,
    "move1Type": "Fire",
    "move1Category": "Special",
    "move2Type": "Normal",
    "move2Category": "Physical",
    "move3Type": "Dark",
    "move3Category": "Physical",
    "move4Type": null,
    "move4Category": null
  },
  {
    "trainerId": "giovanni",
    "trainerName": "Giovanni",
    "locationId": "viridianCity",
    "tier": 8,
    "isGauntlet": false,
    "badgeItemId": "earth-badge",
    "slotIndex": 1,
    "dexId": 111,
    "formName": null,
    "level": 45,
    "move1Power": 100,
    "move2Power": 90,
    "move3Power": null,
    "move4Power": null,
    "move1Type": "Ground",
    "move1Category": "Physical",
    "move2Type": "Normal",
    "move2Category": "Physical",
    "move3Type": null,
    "move3Category": null,
    "move4Type": null,
    "move4Category": null
  },
  {
    "trainerId": "giovanni",
    "trainerName": "Giovanni",
    "locationId": "viridianCity",
    "tier": 8,
    "isGauntlet": false,
    "badgeItemId": "earth-badge",
    "slotIndex": 2,
    "dexId": 51,
    "formName": null,
    "level": 42,
    "move1Power": 100,
    "move2Power": 20,
    "move3Power": 70,
    "move4Power": null,
    "move1Type": "Ground",
    "move1Category": "Physical",
    "move2Type": "Ground",
    "move2Category": "Special",
    "move3Type": "Normal",
    "move3Category": "Physical",
    "move4Type": null,
    "move4Category": null
  },
  {
    "trainerId": "giovanni",
    "trainerName": "Giovanni",
    "locationId": "viridianCity",
    "tier": 8,
    "isGauntlet": false,
    "badgeItemId": "earth-badge",
    "slotIndex": 3,
    "dexId": 31,
    "formName": null,
    "level": 43,
    "move1Power": 100,
    "move2Power": 85,
    "move3Power": 15,
    "move4Power": 60,
    "move1Type": "Ground",
    "move1Category": "Physical",
    "move2Type": "Normal",
    "move2Category": "Physical",
    "move3Type": "Poison",
    "move3Category": "Physical",
    "move4Type": "Fighting",
    "move4Category": "Physical"
  },
  {
    "trainerId": "giovanni",
    "trainerName": "Giovanni",
    "locationId": "viridianCity",
    "tier": 8,
    "isGauntlet": false,
    "badgeItemId": "earth-badge",
    "slotIndex": 4,
    "dexId": 34,
    "formName": null,
    "level": 45,
    "move1Power": 100,
    "move2Power": 120,
    "move3Power": 15,
    "move4Power": 60,
    "move1Type": "Ground",
    "move1Category": "Physical",
    "move2Type": "Normal",
    "move2Category": "Physical",
    "move3Type": "Poison",
    "move3Category": "Physical",
    "move4Type": "Fighting",
    "move4Category": "Physical"
  },
  {
    "trainerId": "giovanni",
    "trainerName": "Giovanni",
    "locationId": "viridianCity",
    "tier": 8,
    "isGauntlet": false,
    "badgeItemId": "earth-badge",
    "slotIndex": 5,
    "dexId": 112,
    "formName": null,
    "level": 50,
    "move1Power": 100,
    "move2Power": 75,
    "move3Power": 90,
    "move4Power": null,
    "move1Type": "Ground",
    "move1Category": "Physical",
    "move2Type": "Rock",
    "move2Category": "Physical",
    "move3Type": "Normal",
    "move3Category": "Physical",
    "move4Type": null,
    "move4Category": null
  }
];

// Returns the roster (array of slot entries) for a trainer at a given tier.
// Pass gauntletOrder (1-5) to get one leg of the Indigo Plateau tier-9 gauntlet.
function getTrainerRoster(trainerId, tier, gauntletOrder) {
  return TRAINERS_DATA.filter(t => t.trainerId === trainerId && t.tier === tier &&
    (gauntletOrder === undefined ? true : t.gauntletOrder === gauntletOrder));
}

// Returns the badge itemId granted by a trainer (same value on every row for that trainerId).
function getTrainerBadge(trainerId) {
  const row = TRAINERS_DATA.find(t => t.trainerId === trainerId && t.badgeItemId);
  return row ? row.badgeItemId : null;
}

// Returns all distinct trainerIds present in the data (for building the gym list).
function getAllTrainerIds() {
  return [...new Set(TRAINERS_DATA.map(t => t.trainerId))];
}
